### ISSUE TITLE
Fixed layout : cannot zoom

### ISSUE THREAD

**Issue by awissam** [edrlab/thorium-reader#1528] opened 2021-08-14 06:05 UTC
hi
i have a fixed layout ePub done on InDesign. is there any workaround to zoom on text in thorium?
thx

**Comment by awissam** [comment] 2021-08-17 08:14
anyone please?

**Comment by danielweck** [comment] 2021-08-17 08:24
Hello, a "zoom" feature for fixed-layout publications will be released soon :)

**Comment by awissam** [comment] 2021-08-17 08:44
is there a version for ios? android?

**Comment by danielweck** [comment] 2021-08-17 10:46
Thorium is a "desktop" application for Linux, Mac and Windows.

**Comment by danielweck** [comment] 2021-08-28 18:12
Duplicate of: https://github.com/edrlab/thorium-reader/issues/1228

**Closed** 2021-09-15 09:35 UTC
