### ISSUE TITLE
EPUB page flipping forward problem

### ISSUE THREAD

**Issue by weiss-d** [edrlab/thorium-reader#1105] opened 2020-06-28 13:51 UTC
Hi!
I've installed 1.3.1-alpha.1.119 on Windows 10 (with latest updates).
When I try to flip pages forward it only flips one page once and then hitting the '>' button or `Right Arrow`  or `Ctrl+.` does nothing. Though flipping backwards works fine.

**Comment by danielweck** [comment] 2020-06-28 15:26
Thank you for reporting this bug. I have been trying to fix it, as this is currently blocking the release.
Closing as duplicate of:
https://github.com/edrlab/thorium-reader/issues/1015

**Closed by danielweck** 2020-06-28 15:26 UTC
