### ISSUE TITLE
When multiple EPUBs are opened, closing one closes all of them

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1123] opened 2020-07-17 08:42 UTC
With EPUB files associated with Thorium, double clicking on an EPUB in Windows File Explorer opens the ebook in a separate instance of Thorium, which is convenient.

However, closing one instance of Thorium immediately closes all opened instances.

**Comment by danielweck** [comment] 2020-07-17 12:08
Hello, thank you for reporting this.
Closing the library / bookshelf window does indeed close all reader windows, by design.
Closing a reader window should not result in other reader windows closing as well.
Closing a single reader window when the library window is displayed should result in the app remaining open.
Conversely, closing a single reader window when the library window is not shown should result in the application exiting.

However, I suspect that there might be issues related to double-clicking on publications from the file explorer, as opposed to drag+drop files into the library window (or using the import button).

Could you please clarify your particular usage pattern? Thank you.

**Comment by danielweck** [comment] 2020-07-17 12:09
Possibly related issue: https://github.com/edrlab/thorium-reader/issues/1124

**Comment by PhilippeBruno** [comment] 2020-07-17 12:19
My particular usage pattern is as follow:

Repeat
- Navigate to desired folder on my Windows 10 machine where the needed EPUB is stored.
- Double click on the EPUB to read it

Until all needed EPUBs are simultaneously opened
- Consult the EPUBs

Then, if I close one, any one, all the opened EPUBs close at once.

**Comment by danielweck** [comment] 2020-07-17 12:47
That’s definitely a UX bug. Thank you for clarifying.
Would you mind testing this, please:
1) import all the necessary publications in the library window (e.g. multiple selection in file explorer, then drag+drop)
2) open first EPUB (reader window appears)
3) reinstate the library window by “detaching” the reader view (icon-button in the top left area of the reader window toolbar)
4) open several more EPUBs from the now- permanently displayed library view
5) close one of the reader windows (not the first, not the last)
6) other windows should remain open

**Comment by panaC** [comment] 2020-07-17 12:56
![image](https://user-images.githubusercontent.com/3198865/87788093-0e7f3780-c83d-11ea-8e14-f6fbdb1a9ce5.png)

the windows are not unlocked with the library window.

Before to fix it, you can bypasses it by a click on the square ("show library").

**Comment by PhilippeBruno** [comment] 2020-07-17 12:57
Ok, @danielweck , your instructions work perfectly. Only the selected EPUB window closes.

**Comment by danielweck** [comment] 2020-07-17 12:58
Thank you, this confirms that the bug can be narrowed down to opening publications via file explorer double-click / open-with, or the command line.

**Comment by PhilippeBruno** [comment] 2020-07-17 13:01
@panaC, yes, I just notice this (I never thought of "detaching" the window before).

@danielweck , yes, but keep in mind @panaC pointed out another key element: detaching the windows. By doing this, even if I open the EPUBs from File Explorer, it will prevent the other windows from closing. For now, this is a workaround, but it should nevertheless be solved.

**Comment by panaC** [comment] 2020-07-17 13:11
we have a problem on the instantiation of a new reader window when the library window is not defined. The first behaviour of thorium didn't allow to launch a reader window without the library already opened. We have to review this process.

**Closed** 2020-10-12 12:10 UTC
Labels: bug, user-interface
