### ISSUE TITLE
pagination selector is editable (arbitrary text can be entered)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2224] opened 2024-05-17 17:24 UTC
<img width="912" alt="Screenshot 2024-05-17 at 18 12 32" src="https://github.com/edrlab/thorium-reader/assets/625201/4f36e046-0a84-4a42-9cba-7e17c1429c14">

**Comment by panaC** [comment] 2024-05-17 17:28
composant change to a combobox need to double check

**Comment by arthur-lemeur** [comment] 2024-05-17 17:49
The problem we faced with the "SHIFT TAB" key combo was caused by the react-aria Select component, I changed it to a Combobox for now to make it work but yes didn't think of this side-effect..

**Comment by panaC** [comment] 2024-05-22 15:30
will be fixed by #2294

**Comment by danielweck** [comment] 2024-05-26 20:30
Fixed by replacing with native selectoption control: https://github.com/edrlab/thorium-reader/pull/2332#issuecomment-2127722233

**Closed** 2024-05-26 20:30 UTC
