### ISSUE TITLE
Thorium Reader is not able to borrow books from an OPDS feed

### ISSUE THREAD

**Issue by vbessonov** [edrlab/thorium-reader#1148] opened 2020-08-18 08:55 UTC
I faced with an issue when Thorium Reader is not able to borrow books from an OPDS feed.

The OPDS feed I'm using: https://github.com/vbessonov/opds-feed

Steps to reproduce:
1. git clone https://github.com/vbessonov/opds-feed
2. cd opds-feed
3. docker-compose up -d
4. Open Thorium Reader and add a new OPDS feed using `http://localhost:8080` as its URL:
![image](https://user-images.githubusercontent.com/6442436/90491873-f8290c00-e159-11ea-82be-d05b6f95ba33.png)
5. Open `Test OPDS feed` catalog and try to borrow a book:
![image](https://user-images.githubusercontent.com/6442436/90491984-1858cb00-e15a-11ea-8065-5547188b6433.png)
6. Thorium Reader opens a `borrow` link in a browser and then stops:
![image](https://user-images.githubusercontent.com/6442436/90492116-3e7e6b00-e15a-11ea-9617-e034d9a6e524.png)

The books wasn't downloaded and isn't accessible in Thorium Reader:
![image](https://user-images.githubusercontent.com/6442436/90492284-7685ae00-e15a-11ea-8b88-a6822a709bf0.png)

**Comment by danielweck** [comment] 2020-08-18 10:09
Thank you very much for the detailed description of the problem.

Thorium does not support PDF publications, so this could be the cause of the behaviour. Would you be able to test with an OPDS feed that serves EPUB publications?

**Comment by vbessonov** [comment] 2020-08-18 10:14
Absolutely, will do

**Comment by CircularKen** [comment] 2020-08-18 10:23
Should that be "Thorium does not *yet* support PDF publications"…?

**Comment by vbessonov** [comment] 2020-08-18 10:33
@danielweck I tried with an EPUB and updated [my repository](https://github.com/vbessonov/opds-feed) accordingly but it worked the same way

**Comment by panaC** [comment] 2020-08-18 10:40
@vbessonov publish the log, please

**Comment by vbessonov** [comment] 2020-08-18 11:06
@panaC, sure but I downloaded the Thorium's binary from the website, could you tell me how I can get the logs?

**Comment by panaC** [comment] 2020-08-18 12:42
https://github.com/vbessonov/opds-feed/blob/15514f87702dff9d3195c03ed4fce8af4a3d315e/content/borrow/index.xml#L29

maybe try to replace href=http://localhost:8080/fulfill/ with http://localhost:8080/fulfill/index.epub

**Comment by vbessonov** [comment] 2020-08-18 15:36
Unfortunately, it didn't work. Basically, http://localhost:8080/fulfill/ gets rewritten by nginx to http://localhost:8080/fulfill/index.epub anyways

**Comment by vbessonov** [comment] 2020-08-19 12:13
@panaC, is there anything else I can do to make it work?

**Comment by vbessonov** [comment] 2020-08-20 13:37
@danielweck, what can I do to speed up the investigation process?

**Comment by panaC** [comment] 2020-10-06 12:12
```
  <entry schema:additionalType="http://schema.org/EBook">
    <title>Dostoevsky Epub</title>
    <author>
      <name>Spec Writer</name>
      <link href="http://cm.hilbertteam.net:6500/MAIN/works/contributor/Spec%20Writer/eng/Adult%2CAdults%2BOnly%2CAll%2BAges%2CChildren%2CYoung%2BAdult" type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="contributor" title="Spec Writer"/>
    </author>
    <simplified:pwid>1ef566f9-bda4-109d-e475-729437d2b6da</simplified:pwid>
    <category term="Adult" scheme="http://schema.org/audience" label="Adult"/>
    <category term="http://librarysimplified.org/terms/fiction/Nonfiction" scheme="http://librarysimplified.org/terms/fiction/" label="Nonfiction"/>
    <category term="http://librarysimplified.org/terms/genres/Simplified/Technology" scheme="http://librarysimplified.org/terms/genres/Simplified/" label="Technology"/>
    <category term="http://librarysimplified.org/terms/genres/Simplified/Architecture" scheme="http://librarysimplified.org/terms/genres/Simplified/" label="Architecture"/>
    <dcterms:language>en</dcterms:language>
    <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973/report" rel="issues"/>
    <id>urn:isbn:9780231543973</id>
    <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973" type="application/atom+xml;type=entry;profile=opds-catalog" rel="alternate"/>
    <bibframe:distribution bibframe:ProviderName="oapen"/>
    <published>2020-08-17T00:00:00Z</published>
    <link href="http://cm.hilbertteam.net:6500/MAIN/groups/142?entrypoint=Book" rel="collection" title="Nonfiction"/>
    <updated>2020-08-17T15:48:41Z</updated>
    <link href="http://localhost:8080/borrow/" rel="http://opds-spec.org/acquisition/borrow" type="application/atom+xml;type=entry;profile=opds-catalog">
      <opds:indirectAcquisition type="application/epub+zip"/>
      <opds:availability status="available"/>
    </link>
    <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973/related_books" type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="related" title="Recommended Works"/>
    <link href="http://cm.hilbertteam.net:6500/MAIN/annotations/ISBN/9780231543973" type="application/ld+json; profile=&quot;http://www.w3.org/ns/anno.jsonld&quot;" rel="http://www.w3.org/ns/oa#annotationService"/>
    <link href="http://cm.hilbertteam.net:6500/MAIN/analytics/ISBN/9780231543973/open_book" rel="http://librarysimplified.org/terms/rel/analytics/open-book"/>
  </entry>
```

2 entry links are extracted from this entry : 

```
[2]   {
[2]     url: 'http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973',
[2]     title: undefined,
[2]     type: 'application/atom+xml;type=entry;profile=opds-catalog',
[2]     properties: undefined
[2]   },
[2]   {
[2]     url: 'http://localhost:8080/borrow/',
[2]     title: undefined,
[2]     type: 'application/atom+xml;type=entry;profile=opds-catalog',
[2]     properties: {
[2]       indirectAcquisitionType: 'application/epub+zip',
[2]       lcpHashedPassphrase: undefined,
[2]       numberOfItems: undefined,
[2]       priceValue: undefined,
[2]       priceCurrency: undefined,
[2]       holdTotal: undefined,
[2]       holdPosition: undefined,
[2]       copyTotal: undefined,
[2]       copyAvailable: undefined,
[2]       availabilityState: undefined,
[2]       availabilitySince: undefined,
[2]       availabilityUntil: undefined
[2]     }
[2]   }
```

the first timeout and the second returns : 

```
<entry xmlns:app="http://www.w3.org/2007/app"
  xmlns:bib="http://bib.schema.org/"
  xmlns:bibframe="http://bibframe.org/vocab/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:drm="http://librarysimplified.org/terms/drm"
  xmlns:opds="http://opds-spec.org/2010/catalog"
  xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"
  xmlns:opf="http://www.idpf.org/2007/opf"
  xmlns:schema="http://schema.org/"
  xmlns:simplified="http://librarysimplified.org/terms/"
  xmlns="http://www.w3.org/2005/Atom" schema:additionalType="http://schema.org/EBook">
  <title>Dostoevsky Epub</title>
  <author>
    <name>Spec Writer</name>
    <link href="http://cm.hilbertteam.net:6500/MAIN/works/contributor/Spec%20Writer/eng/Adult%2CAdults%2BOnly%2CAll%2BAges%2CChildren%2CYoung%2BAdult" type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="contributor" title="Spec Writer"/>
  </author>
  <simplified:pwid>1ef566f9-bda4-109d-e475-729437d2b6da</simplified:pwid>
  <category term="Adult" scheme="http://schema.org/audience" label="Adult"/>
  <category term="http://librarysimplified.org/terms/fiction/Nonfiction" scheme="http://librarysimplified.org/terms/fiction/" label="Nonfiction"/>
  <category term="http://librarysimplified.org/terms/genres/Simplified/Technology" scheme="http://librarysimplified.org/terms/genres/Simplified/" label="Technology"/>
  <category term="http://librarysimplified.org/terms/genres/Simplified/Architecture" scheme="http://librarysimplified.org/terms/genres/Simplified/" label="Architecture"/>
  <dcterms:language>en</dcterms:language>
  <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973/report" rel="issues"/>
  <id>urn:isbn:9780231543973</id>
  <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973" type="application/atom+xml;type=entry;profile=opds-catalog" rel="alternate"/>
  <bibframe:distribution bibframe:ProviderName="oapen"/>
  <published>2020-08-17T00:00:00Z</published>
  <updated>2020-08-17T15:48:41Z</updated>
  <link href="http://localhost:8080/fulfill/" rel="http://opds-spec.org/acquisition" type="application/epub+zip">
    <opds:availability since="2020-08-17T15:52:17Z" status="available" until="2020-09-07T15:52:17Z"/>
  </link>
  <link href="http://cm.hilbertteam.net:6500/MAIN/loans/10/revoke" rel="http://librarysimplified.org/terms/rel/revoke"/>
  <link href="http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973/related_books" type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="related" title="Recommended Works"/>
  <link href="http://cm.hilbertteam.net:6500/MAIN/annotations/ISBN/9780231543973" type="application/ld+json; profile=&quot;http://www.w3.org/ns/anno.jsonld&quot;" rel="http://www.w3.org/ns/oa#annotationService"/>
  <link href="http://cm.hilbertteam.net:6500/MAIN/analytics/ISBN/9780231543973/open_book" rel="http://librarysimplified.org/terms/rel/analytics/open-book"/>
</entry>
```

the publication information view is updated and display this new entry. There is no more a borrow link but an acquisition link. This is why the view changed.
as far as borrow link is concerned, it's not an acceptable mimeType to download it and therefore opens the web browser.

the acceptable mimeType are : 
```
const supportedFileTypeLinkArray = [
    ContentType.AudioBookPacked,
    ContentType.AudioBookPackedLcp,
    ContentType.Epub,
    ContentType.Lcp,
    ContentType.AudioBook,
    ContentType.Json,
    ContentType.JsonLd,
];
```
json and jsonld are only accepted when the format is readium web publication manifest (RWPM) to package it.

I think this behaviour is standard, and i can close this issue.
feel free to reopen it.

**Comment by llemeurfr** [comment] 2020-10-14 07:47
@vbessonov is it finally something NYPL has to correct in its feeds?

**Comment by panaC** [comment] 2020-12-03 15:04
My bad,
It's an issue with opds1 . I think.
Borrow link isn't an alternate opdsEntry.

https://github.com/edrlab/thorium-reader/blob/57b818376fbfe8be99362246abe66e7648c23b56/src/main/converter/opds.ts#L322-L325

What do you think @danielweck ?

**Comment by panaC** [comment] 2020-12-03 15:32
I was wrong on the borrow that opens in the browser.
The issue is here : https://github.com/edrlab/thorium-reader/blob/ac9595581b6c3878d5f8aaabf96cf8eb9351c9a9/src/renderer/library/opds/handleLink.ts#L28
and will be probably fixed with 
https://github.com/edrlab/thorium-reader/blob/b9426c75d376a59b6780a5ea7d61292caa327470/src/renderer/library/opds/handleLink.ts#L25-L29

**Comment by panaC** [comment] 2020-12-03 15:44
tested with : https://github.com/vbessonov/opds-feed ,, it's works now !

**Closed** 2020-12-04 10:55 UTC

**Comment by saad-kh** [comment] 2020-12-04 11:33
Actually https://github.com/vbessonov/opds-feed works with or without the fix, and it works for the wrong reasons. Being a test feed, it tries to loads the alternate link at the address `http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973` which unless to you had setup the the full circulation manager stack locally won't work which triggers a succession of exceptions that ultimately fails at https://github.com/edrlab/thorium-reader/blob/e5fe7f1239aaa9f32c9fe74a0b4f6e08f01e4ed6/src/renderer/common/redux/sagas/dialog/publicationInfoOpds.ts#L47.

**Comment by saad-kh** [comment] 2020-12-04 11:39
Actually https://github.com/vbessonov/opds-feed works with or without the fix, and it works for the wrong reasons. Being a test feed, it tries to load the alternate link at the address `http://cm.hilbertteam.net:6500/MAIN/works/ISBN/9780231543973` which unless you have setup the the full circulation manager stack locally, won't work, and thus it triggers a succession of exceptions that ultimately fails at https://github.com/edrlab/thorium-reader/blob/e5fe7f1239aaa9f32c9fe74a0b4f6e08f01e4ed6/src/renderer/common/redux/sagas/dialog/publicationInfoOpds.ts#L47.

That's where I believe the real issue is. Whenever we open a dialog to show a publication, we try to update it with the content of an entry of `type=entry;profile=opds-catalog` to make it more complete, I can guess. 

However in our case, the alternate link points to the original non protected entry that has the borrow link and not the newly acquired protected one with the real acquisition link. Thus we stop having an acquisition link and start re-having the borrow link after this sync procedure finish.
