### ISSUE TITLE
EPUB: monospace rendering for code examples

### ISSUE THREAD

**Issue by weiss-d** [edrlab/thorium-reader#1106] opened 2020-06-29 07:40 UTC
Reading some programming books in EPUB format, I thought it would be cool to render code snippets, that are styled in CSS accordingly, in monospace font.

![Annotation 2020-06-29 103043](https://user-images.githubusercontent.com/62437174/85985837-fb263c80-b9f3-11ea-95df-db3113f3287d.jpg)

**Comment by danielweck** [comment] 2020-06-29 21:03
Hello, I am not able to reproduce this problem with the default user settings, which do not override the authored font faces. However, as a user if I choose to override the publisher styles with a custom font, then this is applied to all text, including the monospace code sections. @JayPanoz this sounds like something that is controlled by https://github.com/readium/readium-css right?

**Comment by weiss-d** [comment] 2020-06-30 04:52
@danielweck, sorry, looks like I have instinctively switched the font because default one looks so  Windows9x-ish and it's hard to read, I honestly don't remember when I did this 🙄
And default monospace is almost disappearing on 1920x1080 display.
It wood be so cool if it could override fonts by category, e.g. Fira Sans for sans serif, Fira Code for monospace etc.

![image](https://user-images.githubusercontent.com/62437174/86084905-9e378e80-baa6-11ea-8d33-05a95b869d90.png)

**Comment by JayPanoz** [comment] 2020-06-30 08:51
> this sounds like something that is controlled by https://github.com/readium/readium-css right? 

Indeed but we’re only applying `font-family` to [a subset of HTML elements](https://github.com/readium/readium-css/blob/master/css/src/modules/user-settings-submodules/ReadiumCSS-fontFamily_pref.css), which doesn’t contain markup elements for code, etc. 

So it seems to me the user setting is applied to code because it’s using `p class` in this publication. If the markup in the book was using `pre + code` it shouldn’t have been overridden.

That said, it wouldn’t solve this rendering issue raised by @weiss-d 

> And default monospace is almost disappearing on 1920x1080 display. It wood be so cool if it could override fonts by category, e.g. 'Humanist' for sans serif, 'Monospace' for monospace etc.

That’s quite tricky with CSS only since emulating defaults (for `sans-serif`, `serif`, `monospace`, `script`, etc.) is not really a thing it was meant for. It’s more of an app concern as they have easier access to that (+ installed fonts) and then there’s the issue of force-overriding the authors’ stylesheets (cf. browsers). 

![Capture d’écran 2020-06-30 à 10 49 21](https://user-images.githubusercontent.com/12599652/86105302-730d6900-babf-11ea-857e-caa81239c2f7.png)

But I can imagine Electron has something for that?

**Comment by henrietteBaum** [comment] 2021-08-13 09:04
It seems I have a similar problem:
I read books that contain code snippets in a monospace font. In order to still be able to read something, I have to greatly enlarge the font, but the code display remains very small in places. Also, the contrast in these areas is too weak. Changing the font and size in the settings does not change anything.

![image](https://user-images.githubusercontent.com/67079945/129332682-049f6f07-83ed-48f3-a922-3aeb3524173b.png)

(Thorium-Reader on Windows 10)

Even though I can read the "normal" text with the screen reader, it is better understanding to read the code examples myself.

Helpful would be therefore:
- a possibility to increase the font size of code examples.
- a better contrast for the areas

But otherwise this is a really nice program, thanks!

**Comment by danielweck** [comment] 2022-08-26 18:15
Moving to https://github.com/readium/readium-css/issues/112

**Closed by danielweck** 2022-08-26 18:15 UTC
Labels: enhancement, css
