### ISSUE TITLE
Touch screen zoom on windows 10

### ISSUE THREAD

**Issue by quiquegurdiel** [edrlab/thorium-reader#1676] opened 2022-04-18 15:30 UTC
It seems there is no way to make zoom from a touch screen using a gesture, at least in v1.8.0 on windows 10.

I used a medion (akoya p2211t) that works both as a laptop and as a tablet because the touch screen is detachable (same as a microsoft surface), running version 1.8.0 on windows 10. I've seen that I can control the zoom from a laptop using the touchpad as usual, which is very practical, but I can not do the same using the touch screen (as when you zoom in a mobile phone) so when it's used as a tablet there's no way to zoom efficiently. Just in case, it seems something related with touch screens in general, not with the fact that in my case it can be detached. In other programs that the zoom control works fine from the screen it acts indepently of being attached or not.

**Comment by danielweck** [comment] 2022-04-21 16:48
Duplicate of https://github.com/edrlab/thorium-reader/issues/725

**Closed by danielweck** 2022-04-21 16:48 UTC
