### ISSUE TITLE
LCP / UX better experience if loan extension reaches the limit

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#893] opened 2019-12-18 13:25 UTC
This appears if one requests a loan extension after the limit. 

<img width="318" alt="Capture d'écran 2019-12-18 14 24 02" src="https://user-images.githubusercontent.com/14943186/71089903-10e3bb00-21a2-11ea-9686-c2b43464f6b5.png">

A better message is: 
"It is not possible to extend the end date of the license after February 3, 2020"

**Comment by llemeurfr** [comment] 2019-12-18 13:27
It would also be better to allow an extension up to the limit, if the extension date is greater than this limit. The potential rights end information in the status document provides this information.

**Comment by danielweck** [comment] 2019-12-19 10:25
> A better message is

The screenshot shows the message extracted from the HTTP `403` response body. This message is not generated by Thorium.
However, I agree that we could probably just capture `403` status code (or any `40x`), and interpret this as a rejection, and generate a more human-friendly message based on the LSD `potential_rights`.

**Comment by danielweck** [comment] 2019-12-19 10:46
Note do devs (HTTP status code / error string-ification): 
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/services/lcp.ts#L341-L350
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/services/lcp.ts#L943-L953

**Comment by llemeurfr** [comment] 2021-09-02 14:26
I would agree to keep the server-generated message, as long as we process HTTP Problem Details cleanly with a proper accept-language parameter. 

I can make sure that the open-source LCP Server still processes accept-language properly.

**Comment by danielweck** [comment] 2022-08-26 17:55
Duplicate of https://github.com/edrlab/thorium-reader/issues/540

**Closed by danielweck** 2022-08-26 17:55 UTC
Labels: LCP
