### ISSUE TITLE
Win10 (not MacOS) PDF import error of "no such path in zip: cover.png" for many PDFs - example file linked to.

### ISSUE THREAD

**Issue by byjosh** [edrlab/thorium-reader#1939] opened 2023-04-03 15:51 UTC
Can't see an open issue or closed issue that is this - though #1335 may relate to underlying cause. Hope I have given necessary detail to replicate.

With the PDF at [https://www.vmware.com/content/dam/learn/en/cloud/pdf/Managing_Kubernetes_eBook.pdf](https://www.vmware.com/content/dam/learn/en/cloud/pdf/Managing_Kubernetes_eBook.pdf) with a sha256 hash of b4cc83bd201640ef625ac261021d9dc29b3c8992793fe9e454d2ba4e1fe578f9 - saved in an ordinary location of C:\Users\cis\Downloads  on Windows 10 (Pro and Home versions)
I get the import  of the PDF into Thorium failing with the message of "no such path in zip: cover.png".

This actually happens with quite a few other PDFs (often O'Reilly developer publications) - hence filing a bug report - the example file is just one that is publicly available. Firefox builtin PDF reader will show the cover loading fine (example file) or not (some other files). 

This error is with Thorium version 2.2.0.0 Windows Store version and Github installer version running on Windows 10 version 22H2 build 19045.2728, Windows Feature Experience Pack 120.2212.4190.0 . That version and build number is for a Win 10 Pro machine I initially tried on but using Windows Store version of Thorium  I replicated on a Win 10 Home machine with same Windows version (22H2) and build number. So it is not just the particular machine I first tried this on. 

On the PDFs where Firefox's reader does not load the cover fully - but does read the rest of the PDF (indicating the issue may be an ungraceful failure) - Microsoft Edge is able to read the cover OK (the O'Reilly Programming Rust title is an example of a file I saw this behaviour with). I see from #1335 there are various PDF.js versions involved - in Firefox (v 111.0.1)  this does not result in the tab closing and the rest of the PDF is viewable and readable even if the cover does not show correctly on some files - in Thorium the window closes and the import fails (so to read these PDFs Firefox or Edge would be required on Windows 10). So Thorium & PDF.js is issue not just PDF.js in any setting.

The error does not occur on MacOS Big Sur using the Thorium Github Mac installer (v.2.2.0) - and sha256 hash is the same for both copies of the file downloaded (my first thought was a corrupted download but the hash values being the same I think means that can be ruled out). 

As the file name and location is very standard and does not contain characters one would not find on a US/UK keyboard I doubt this is an issue with the path or filename or a failure to cope with non-English characters.

I hope with the example file & hash value, the Thorium and Windows version info and having verified it on more than 1 machine I have provided enough info to make this a replicable bug.

**Comment by danielweck** [comment] 2023-04-03 17:19
Hello, thank you very much for your detailed description of the problem. Could you please download and try the "latest windows" build of Thorium:
https://github.com/edrlab/thorium-reader/releases

**Comment by byjosh** [comment] 2023-04-03 17:45
Hi,
I installed the 2.3 alpha from build run [4499631425](https://github.com/edrlab/thorium-reader/actions/runs/4499631425) and that displays the same behaviour: opens but then closes the sample PDF (so that one cannot actually read it in Thorium unlike in Firefox or Edge) and fails to import it is with "no such path in zip: cover.png" message. That was under Win 10 Home (Win 10 version/build as above).

So current 2.3 branch does not seem to fix it. My observation is that the example file maybe is considered malformed by some standard (Thorium loading other files -  ebooks that seem to have covers - just fine). So a combination of PDF structure knowledge, Thorium debugging knowledge (which I don't have) and PDF.js debugging (likewise I don't have) might reveal how to fail less catastrophically/more gracefully with this kind of file. 

The one thing I can do is: having a copy of Acrobat Professional I think that shows me a bit of the document structure - I'll examine the test file and another one that imports fine and see if I spot any obvious difference (e.g. if it is specifies the cover image differently in the problem file vs functioning file).

**Comment by danielweck** [comment] 2023-08-01 20:51
Hello, could you please try again with the latest automated test build:

 https://github.com/edrlab/thorium-reader/releases

**Comment by danielweck** [comment] 2023-08-03 17:18
Hello, I am unable to reproduce this behaviour with Thorium v2.3.0 on Windows 11 (see attached screenshots).
I am closing this issue, but please feel free to chime back in for further feedback. Thank you!

![Screenshot 2023-08-03 180959](https://github.com/edrlab/thorium-reader/assets/625201/78881696-fc50-4551-af11-371e0a7e4d69)
![Screenshot 2023-08-03 181026](https://github.com/edrlab/thorium-reader/assets/625201/46d79f22-fc1a-4102-ac73-1494ea4f0a87)
![Screenshot 2023-08-03 181052](https://github.com/edrlab/thorium-reader/assets/625201/c6ff5e17-2935-4998-b283-61fe67580a2d)

**Closed by danielweck** 2023-08-03 17:18 UTC

**Comment by byjosh** [comment] 2023-08-15 17:33
Hi I did test the build you indicated on my Windows 10 setup without success - but if you previously had an error on Windows 11 and with the new build the error has gone then that is some progress.
