### ISSUE TITLE
Page turn forward / right arrow at end of document or sometimes middle of text, does not work in some HTML documents (scroll and paginated modes)

### ISSUE THREAD

**Issue by cenkt** [edrlab/thorium-reader#1015] opened 2020-04-23 10:25 UTC
Hi, The page forward arrow key stops functioning after turning 2 pages forward. But the back arrow key works just fine. Any suggestions 

Os: Windows 10.
Thorium version: 1.2.1

**Comment by cenkt** [comment] 2020-04-25 09:11
Hi again anyone else experiencing this problem or am I doing something wrong?

**Comment by nvdaes** [comment] 2020-04-25 19:02
If you are talking about control+avPag and control+rePag, this doesn't work always for me. Seems that the focus needs to be placed in some area or the system needs to be refreshed in some way.

**Comment by cenkt** [comment] 2020-04-25 19:06
No I am talking about all page forwards. Mouse keyboard arrows and keyboard short cuts. None work

**Comment by nvdaes** [comment] 2020-04-26 05:37
OK. Then, what I can say is that I use NVDA's screen reader and for me keys like arrow, avPag, etc. in browse mode work well. The issue is that I need to press control+home to ensure that contro+av/rePag will always work or Escape to focus the navigation menu in case i is pressed. I don't know if your isse could cover other related problems about shortcuts.

**Comment by cenkt** [comment] 2020-04-29 19:50
Still no luck with the forward key and/or arrows. I can navigate backwards with no problem but can not move forward even with the new version..

**Comment by panaC** [comment] 2020-04-29 19:59
can you share your publication or explains how to reproduce the issue ? Thanks

**Comment by cenkt** [comment] 2020-04-30 06:42
Hi as you can see in the GİF file you can turn pages backwards but for forward page turning the app gets stuck after one turn....
Again:
Windows 10 Pro 1909
Dell XPS13 9360
Thorium version: 1.3.0



![20200430_093813](https://user-images.githubusercontent.com/6926806/80679877-6e7c0280-8ac6-11ea-868d-f3d4d54c8e66.gif)

**Comment by danielweck** [comment] 2020-04-30 06:58
Does this happen with any "chapters" (i.e. individual HTML documents in the reading order)?
Does this happen with one particular EPUB?

**Comment by cenkt** [comment] 2020-04-30 07:20
Any book any chapter ...

Sent from my iPhone

On Apr 30, 2020, at 09:58, Daniel Weck <notifications@github.com> wrote:

﻿

Does this happen with any "chapters" (i.e. individual HTML documents in the reading order)?
Does this happen with one particular EPUB?

**Comment by danielweck** [comment] 2020-04-30 07:57
I am sorry, but I have just tried Thorium 1.3.0 from the Windows Store and I am unable to reproduce the issue you describe. My main computer is a Mac, and I am able to turn pages back and forth without any issues, using the keyboard's left/right arrow keys, or mouse click on the previous/next buttons (bottom right UI corner).

**Comment by cenkt** [comment] 2020-04-30 08:13
:( could be a Windows thing or Hi-dpi thing. Anyways I will update if thing change. Thnks

**Comment by nvdaes** [comment] 2020-04-30 08:56
Unfortunately this is not predictable. Seems this is related to the
detection of a previous refresh or cursor movement in the document.
Sometimes it works better after pressing control+home or focusing the
toolbar (control+t) but not always works well after this.
It seems work worse when trying to do it quickly. But there is nothing
which indicates where the document is available to receive
control+avPag or control+rePag.

2020-04-30 8:58 GMT+02:00, Daniel Weck <notifications@github.com>:

**Comment by nvdaes** [comment] 2020-05-01 03:31
Hello, I will open a different issue for my problem with controlàvPag
and repag, since sometimes I don't know what we are talking about :)

2020-04-29 21:59 GMT+02:00, Pierre Leroux <notifications@github.com>:

**Comment by peaceroad** [comment] 2020-05-05 05:08
When the display scaling of Windows was changed and the contents of xhtml were pushed out of the vertical direction of the screen, I could not move to the next page by pressing the right arrow key on the second page of the contents of xhtml. The problem also occurs in scroll mode.
However, if the display scaling in Windows was 100%, I didn't have this problem.

**Comment by cenkt** [comment] 2020-05-05 10:56
My scaling is %225 due to Hi dpi. However when I switched to 100% I was not able to turn pages.

**Comment by danielweck** [comment] 2020-06-08 15:12
I've been able to reproduce this easily in the latest automated build, with reflowable books in Windows (not on Mac). Both scroll and paginated modes. TTS readaloud turns to the next HTML document without any issues.

**Comment by danielweck** [comment] 2020-06-28 15:25
From @weiss-d

https://github.com/edrlab/thorium-reader/issues/1105

Hi!
I've installed 1.3.1-alpha.1.119 on Windows 10 (with latest updates).
When I try to flip pages forward it only flips one page once and then hitting the '>' button or `Right Arrow`  or `Ctrl+.` does nothing. Though flipping backwards works fine.

**Comment by danielweck** [comment] 2020-06-28 23:15
Hello all, there's a new test build available at https://github.com/edrlab/thorium-reader/releases

Reminder: these builds are automatically generated by the CI / Continuous Integration service(s), based on the `develop` branch which includes a workaround for this annnoying CSS pixel bug / edge case. In my tests on a physical laptop as well as on virtual machines (all latest version of Windows 10), I observed different outcomes depending on screen resolution / DPI, and also the size of the application window.

So, could you please test Thorium with the EPUBs that were causing problems, and please report back to us here?

Many thanks!
Regards, Daniel

**Comment by weiss-d** [comment] 2020-06-29 03:49
Hi! I have Win 10 Pro laptop, 1920x1080, 125% scale.
In windowed mode problem persists — I can only flip a page forward once and then is stops flipping, only moves all text back and forth in a second for a couple of pixels, **but** when I switch to the fullscreen, everything works perfectly, forwards and backwards.

**Comment by danielweck** [comment] 2020-06-29 07:44
Hello @weiss-d is that in scroll or paginated mode? Does it happen in the middle of a chapter document, or at the very end? Could you please share an EPUB that exhibits this behaviour?
Many thanks!

**Comment by weiss-d** [comment] 2020-06-29 07:50
It happens only in paginated mode in the arbitrary place of document.
I will send you a couple of EPUBs via email.

**Comment by danielweck** [comment] 2020-06-29 20:47
Thank you @weiss-d for sharing the EPUB, I was able to occasionally reproduce the bug on my Windows tablet. I used the same DPI settings as usual, but I resized the application window in single or two-page spread paginated mode (as well as scroll, just to make sure I wasn't missing regressions in this mode), until I was able to reproduce the bug. I debugged the CSS offset values which are sometimes fractional CSS pixels on the edge of a calculated boundary (like a page / CSS column border, or end of document). I wrote some arithmetics to normalize the values, and this seems to have solved the problem without introducing regressions. After I validated the implementation on Windows, I checked it on Mac OS as well (not Linux).

So, may I please ask you all (in this discussion thread) to download and test the latest build from:
https://github.com/edrlab/thorium-reader/releases
(the build is being created by the CI server, as we speak .. so this will be the incremental number after `Thorium_Setup_1.3.1-alpha.1.121.exe` ... )

**Comment by weiss-d** [comment] 2020-06-30 04:27
@danielweck thanks a lot! In 1.122 I can turn pages normally either in windowed and fullscreen mode 👍

**Comment by danielweck** [comment] 2020-06-30 14:20
That's good news, Simon. Thank you for reporting. Others? Feedback please :)
In the meantime, I am working on a couple of other features / bugfixes for the impending Thorium release.

**Comment by danielweck** [comment] 2020-07-01 10:29
Okay, I am closing this issue on the basis that I and Simon are not able to reproduce the bug. Others: feel free to re-open the issue if the problem still occurs.

**Closed by danielweck** 2020-07-01 10:29 UTC
Labels: bug
