### ISSUE TITLE
New feature: utilization data & analytics

### ISSUE THREAD

**Issue by mutterback** [edrlab/thorium-reader#695] opened 2019-09-10 16:27 UTC
We've begun working on utilization data tracking and analytics for Readium Desktop

Our initial approach is to use Microsoft App Insights., which supports a standard "telemetry" events and custom events we can add. Here is an initial list of events we're working to capture and then report, below:

Feedback on how best to grab the custom event data data would be much appreciated. The highest priority events where we're having difficultly are Book opens (including title of the EPUB or consistent UUID) and page turns. 

We'd also like to make this generally useful to others and are open to feedback on additional events and data that would be important to you.

Custom events (Readium):
List of titles in library
App language
Change Configuration (theme, text, display)
Pageviews
Open App
Close App
**Open Title** (need to get EPUB Title or consistent UUID across apps)
Close Title
**Turn page**
Time on task
Add Title to library
Delete title from library
Download title
Download LCP title

Accessibility custom events:
Launch TTS
Time on TTS
Play Video
Video file title
Play audio
Audio file title

Default Telemetry from App Insights:
Processor
RAM
HDD Space
Computer Name
OS
OS Version
User Name (currently not supported by app)
Region
IP (may not work with Node.js)
App version
Windows Serial Number (may not work with Node.js)

Exceptions:
HTTP responses
Errors thrown
Warnings

**Comment by danielweck** [comment] 2019-09-10 17:27
Just wondering: have you had any thoughts about "learning analytics", more specifically IMS Caliper?
(I imagine integrating this would require a deeper dive into the Readium "navigator" component)

Sample code:
https://github.com/IMSGlobal/caliper-js
https://github.com/IMSGlobal/caliper-js-example

Specifications:
https://www.imsglobal.org/caliper-analytics-v11-introduction
https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html

Documentation hub:
http://www.imsglobal.org/activity/caliper

Related reading:
https://er.educause.edu/articles/2019/5/21st-century-analytics-new-technologies-and-new-rules
https://eliterate.us/learning-engineering-a-caliper-example/

Legacy / old references (EDUPUB / EPUB-For-Education):
https://w3c.github.io/publ-cg/education/epub-education.html#ims-learning-tools
http://www.imsglobal.org/caliper/caliperv1p0/ims-caliper-analytics-implementation-guide

**Comment by danielweck** [comment] 2019-09-10 18:10
Thank you Matt for your draft proposal, which is a great start.

A few thoughts:

* Support for analytics in Thorium / `readium-desktop` requires implementing an "event hub" API that centralizes the definition of possible messages (semantics), and that manages the associated queue traffic (throttle/debounce, non-blocking async operations, network online/offline resilience, etc.).
* This should be an opinionated API with a limited functional perimeter, driven by the guiding principle that we should only expose domain-agnostic behavioral data (in other words, no need to go deep into learning experiences semantics / student interaction patterns, etc.).

That being said, I feel it is useful in the context of this discussion to reference existing / past efforts that have at some point (or maybe still have) relevance in EPUB digital publishing (and reading systems). Which brings me to xAPI (TinCan API):

https://github.com/adlnet/xAPI-Spec
https://www.adlnet.gov

Just as with the IMS Caliper reference in my previous comment, I am not necessarily recommending that we implement support for any of these domain-specific technologies, but I just thought it would be useful to have a clearer bigger picture, so that we can make well-informed decisions about the "out of scope" functionality.

**Comment by danielweck** [comment] 2019-09-10 18:27
Regarding "page turns" events, I am wondering if this could be used:
https://github.com/readium/readium-desktop/blob/9799be240bd18a6dde9bc064b8c762e77953d08b/src/renderer/components/reader/Reader.tsx#L550-L557

This event callback is invoked by the `r2-navigator-js` component, and it is debounced. In other words, when the "reading location" changes many times at short intervals within a limited period of time, only the trailing occurrence is fired.

The event payload (i.e. function argument) contains information about the "reading location", including data about synthetic column-based pagination (not available in scroll mode).

The "reading location" change-event is triggered when the user follow hyperlinks, during scroll using the mouse wheel, when document formatting options are altered (e.g. font size), etc. So there would need to be some filtering mechanism if the "page turn" event of the analytics API was designed to convey "pure" "page turn" events, such as when the user explicitly invokes the "previous" / "next" commands ... which leads me to:

Alternatively, user interaction can be detected at this level:

https://github.com/readium/readium-desktop/blob/9799be240bd18a6dde9bc064b8c762e77953d08b/src/renderer/components/reader/Reader.tsx#L341-L371

**Comment by dobbz** [comment] 2019-09-19 19:55
@danielweck 

We really appreciate the feedback.

We have already made some progress with windows application insights in gathering some data. We chose it because it provides simpler methods to collect metrics as well as telemetry data.

Currently we can already get types of events like book open and page turns from the readium apps because they issue GET requests which are collected by default. 

Here is a sample of what we collect

```
timestamp [UTC] | 2019-09-03T20:07:05.561Z
-- | --
  | id | \|f882361759b349fdb546d68605dae227.
  | name | GET /pub/QzpcVXNlcnNcQ2hyaXN0b3BoZVxBcHBEYXRhXFJvYW1pbmdcZUtpdGFidS5lS2l0YWJ1ZVJlYWRlclxwdWJsaWNhdGlvbnNcMjQ1YzUxZWUtOWYwOS00ZTZiLTlkMzEtNGVlNDA5YmJhY2YxXGJvb2suZXB1Yg%3D%3D/manifest.json
  | url | https://127.0.0.1:8000/pub/QzpcVXNlcnNcQ2hyaXN0b3BoZVxBcHBEYXRhXFJvYW1pbmdcZUtpdGFidS5lS2l0YWJ1ZVJlYWRlclxwdWJsaWNhdGlvbnNcMjQ1YzUxZWUtOWYwOS00ZTZiLTlkMzEtNGVlNDA5YmJhY2YxXGJvb2suZXB1Yg%3D%3D/manifest.json
  | success | True
  | resultCode | 200
  | duration | 8
  | performanceBucket | <250ms
  | itemType | request

```
What would you recommend as a way of decoding the URI string?

**Comment by danielweck** [comment] 2019-09-23 11:58
I do not think that HTTP requests can be used as reliable indicators of "page turn" occurrences, because "turning the page" inside an already-loaded HTML document does not necessarily result in an HTTP request, and even if it did, the document may be fetched from cache (i.e. spine item with all its associated image/CSS/fonts/etc. resources).
It would be better to expose actual "page turn" events, emitted by the "navigator" component of the Readium architecture (this would work in fixed-layout publications, as well as reflowable ones in scroll and paginated modes).

As for the "book open" event, I think that requests to `manifest.json` can be cached too (at the HTTP level), but also in a given "streamer" instance. So this seems like a brittle approach to me. Once again, to avoid fallible guesswork, I would prefer to expose a proper "book open" event, emitted from the app layer (e.g. when transitioning from the library view to the reader view, or when using the CLI).

As for interpreting the URI, you can simply decode base64:

`QzpcVXNlcnNcQ2hyaXN0b3BoZVxBcHBEYXRhXFJvYW1pbmdcZUtpdGFidS5lS2l0YWJ1ZVJlYWRlclxwdWJsaWNhdGlvbnNcMjQ1YzUxZWUtOWYwOS00ZTZiLTlkMzEtNGVlNDA5YmJhY2YxXGJvb2suZXB1Yg==`

=>

`C:\Users\Christophe\AppData\Roaming\eKitabu.eKitabueReader\publications\245c51ee-9f09-4e6b-9d31-4ee409bbacf1\book.epub`

:)

In the "desktop" implementation of the Readium architecture, this is the filesystem location of the EPUB file served by the "streamer" component. More specifically in Thorium, this is a well-defined path created by the app (note that the publication filename is always `book.epub`, and the containing folder is a UUID)

**Comment by brettins** [comment] 2019-10-25 20:38
Hey @danielweck - I'm looking into implementing this stuff right now. The Caliper framework looks great as an overall wrapper for the way to log events. Is it something you would see as beneficial to be added to the overall Readium setup? 

From my limited understanding, I think I would just implement this in whatever way you recommended and would be most generally useful to everyone using Readium, and then customize it for our own use after that is set up. 

Is the Caliper sample app you linked a good starting point for setting up something to implement the 'event hub' API in readium? Or if not, is there any example that I could start digging into?  My work with this type of application is still pretty limited, but if I have the fundamentals of structure I can implement this in whatever way you think is best.

**Comment by danielweck** [comment] 2019-10-26 09:17
My understanding of Caliper etc. is quite superficial, so I do not have strong recommendations. Perhaps we could start with a simpler vocabulary / protocol, based on the principles of existing long-established libs, like Caliper?

**Comment by brettins** [comment] 2019-10-28 17:05
Sounds good. Do you have suggestions of what I should look to in building an event HUB API to handle events for analytics? I'm still learning the project so I'm not sure where in the code structure I would start.

**Comment by danielweck** [comment] 2019-10-28 18:03
For "reading location" changes, I would add a handler function in:
https://github.com/readium/readium-desktop/blob/a7c90060500e280de5328e458e89c5a55549e0fd/src/renderer/components/reader/Reader.tsx#L597-L604
There is some documentation here:
https://github.com/readium/r2-navigator-js/blob/develop/README.md#reading-location-linking-with-locators
I think `LocatorExtended.paginationInfo` would be quite useful to detect actual "page turns".

**Comment by panaC** [comment] 2020-10-14 14:28
may I close the issue ?

**Comment by danielweck** [comment] 2020-10-14 19:14
The contents of this discussion thread are valuable, but this is not really an actionable issue, it is more like a useful resource which should be in a wiki page. At this juncture, I think that eKitabu have developed a number of "hooks" into application/user behaviour in order to feed events into an analytics engine. I do not think we have a consensus to implement a well-defined analytics API in Thorium at this stage, so I am in favour of closing this issue. The contents are not lost, just in case we need to revisit this decision for Thorium "v-next" :)

**Closed by danielweck** 2020-10-14 19:14 UTC
Labels: question
