### ISSUE TITLE
PDF import error: no such path in zip cover.png

### ISSUE THREAD

**Issue by mbishop98** [edrlab/thorium-reader#2391] opened 2024-05-28 19:59 UTC
Hello! I'm new to using Thorium and I am trying to upload a PDF, but I keep getting the same error message (even when different PDFs are uploaded): no such path in zip: cover.png. Any help is appreciated!

**Comment by mbishop98** [comment] 2024-05-29 17:12
Hello,

Attached is one of the PDFs I was trying.

Thanks for your help,
Megan


Megan Bishop (she/her)
Project Manager
Book Publishers Association of Alberta

email: ***@***.***

phone: 780-424-5060
Read Aberta!<http://readalberta.ca>

________________________________

**Comment by danielweck** [comment] 2024-05-29 17:15
there was no attachment, could you please send me an email? daniel.weck@gmail.com

**Comment by danielweck** [comment] 2024-05-29 17:52
Hello, I am unable to reproduce this problem using the PDF you provided...however, I am on MacOS and there was a similar bug report on Windows (I personally wasn't able to reproduce on Windows either):

https://github.com/edrlab/thorium-reader/issues/1939

So, are you on Windows 10 or 11?
Are you using Thorium 2.4.2 (the latest official release) or Thorium 3 "beta" versions?
Could you please try with an installer from https://github.com/edrlab/thorium-reader/releases

Thank you!

**Comment by 5tev3G** [comment] 2024-06-08 03:45
I too have the same problem on mac using the Thorium 2.4.2 build

**Comment by danielweck** [comment] 2024-06-08 07:11
hello @5tev3G that's really interesting, as we are assuming that this is a Windows problem. Would you mind sharing your PDF with me at daniel.weck@gmail.com so I can attempt to reproduce the bug and troubleshoot at my end? By the way, what version of Mac OS are you running?

**Comment by 5tev3G** [comment] 2024-06-19 04:26
Hi ! This PDF for example has exhibits the error: https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf

OS: Sonoma 14.4

**Comment by danielweck** [comment] 2024-06-19 08:22
Hello [5tev3G](https://github.com/5tev3G) I am not able to reproduce the bug on my MacBook (Intel)
Sorry :(

**Comment by panaC** [comment] 2024-07-01 13:41
I'm not able to reproduce too on my Macbook m1.
Could you test on the last release : Thorium 3.0 please.
I'm closing the issue for the moment, feel free to reopen it.

**Closed by panaC** 2024-07-01 13:41 UTC
