### ISSUE TITLE
Blank screen on all EPUB files on Windows 10

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1284] opened 2020-12-17 16:12 UTC
A user downloaded Thorium 1.5  and installed it on a new Windows 10 system  (Version 10.0.19042, i.e. 20H2, i.e. the latest version).

His message: "all it shows is a blank screen, although i see table of contents and the reader moves to pages selected in refuses to display"

I sent him moby-dick.epub for test = same behavior.

**Comment by danielweck** [comment] 2020-12-18 23:05
My Windows 10 OS is at 20H2 as well (latest updates). I am not able to reproduce this bug.

> A user downloaded Thorium 1.5

Standalone installer downloaded from the GitHub release page, or Windows Store install?

**Comment by danielweck** [comment] 2020-12-18 23:11
Note that I tested the Windows Store app only, with my already-installed version, and also "from scratch" (I uninstalled the app, and deleted the settings folder)

**Comment by llemeurfr** [comment] 2020-12-19 09:55
The user tried both the Windows Store installer and the version provided via Github. Same result.

**Comment by panaC** [comment] 2020-12-30 16:01
we don't have any clue to fix it, perhaps it better to close it

**Closed** 2022-08-23 10:50 UTC
