### ISSUE TITLE
Body tag CSS background colour overspilling declared viewport size

### ISSUE THREAD

**Issue by raxelbrof** [edrlab/thorium-reader#1529] opened 2021-08-17 06:21 UTC
Hi,

This is an issue for Fixed-Layout EPUB:

Observed behaviour: If I define a background colour for the body tag on a page whose viewport is defined as a fixed size, the background colour is extending to the edges of the Thorium window viewport, and not ending at the edges of the document declared viewport.

Expected behaviour: The background colour of the Body tag, and indeed the rendering of any element or CSS should be cropped to the viewport, as declared in the meta tag for the page.

Thorium should handle the background colour of its viewport canvas outside of the document's declared viewport as a separate thing.

**Comment by danielweck** [comment] 2021-08-17 06:27
Hello, thank you for the detailed explanation. Would you mind posting a screenshot that demonstrates the problem? Thank you very much!

**Comment by raxelbrof** [comment] 2021-08-17 06:55
No problem, as per image here - the cover art shown is scaled to the full width of the declared viewport, and the grey is the body's background colour.

What should be happening is the grey should stop where the cover art stops in the horizontal axis, because the declared viewport should be a hard limit for the rendering or extent of any element in the EPUB. When you fist open a book it's not evident, because Thorium opens its documents windows scaled to the declared viewport proportions, but unlike iBooks / Apple Books, Thorium lets you drag a document window to a different window proportion from the declared viewport size / scale.

If you narrow Thorium's window horizontally to the point where the declared viewport scales to be shorter than the Thorium window, you see the same problem in the vertical axis.

![thorium_viewport](https://user-images.githubusercontent.com/64583201/129676520-1e24470b-283f-4fe8-baf7-a22f564a0b5e.png)

**Comment by danielweck** [comment] 2021-08-17 07:01
Thank you! By any chance, would you be able to privately share a fixed layout EPUB that exhibits this problem? I would like to check the markup and run some tests myself.

**Comment by raxelbrof** [comment] 2021-08-17 07:03
No problem, I can build you a test version - what's the best way to share it?

**Comment by raxelbrof** [comment] 2021-08-17 07:46
Here's a version with all the real content stripped, and replaced with cats, it'll demonstrate the issue.

[thorium_tester.epub.zip](https://github.com/edrlab/thorium-reader/files/6997973/thorium_tester.epub.zip)

**Comment by raxelbrof** [comment] 2021-08-17 10:02
FWIW I found a solution, which is to apply the background colour for the page with a div set to 100% width & height, rather than to the body itself. It may be that the body expanding to the window extents beyond the declared viewport is a standard Webkit (or whatever engine) behaviour, that you just don't encounter with iBooks / Apple Books.

**Comment by danielweck** [comment] 2021-08-17 10:08
Thank you for sharing a sample EPUB, this helped me a lot to troubleshoot this issue!

Thorium "resizes" FXL HTML documents using a CSS 2D transform (scaling + translation) so that fixed layout pages fit within the viewport as per the authored page spread hints. Unfortunately this CSS transform doesn't account for background image or color. I found a workaround, but the method isn't without its caveats:

`background: unset !important;`
+
`background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=) !important;`
(1px transparent image)

This style is injected on the root `html` element, which works fine where there is an authored background color for the `body`, but this breaks when content creators style the `html` root element instead. I think this is an acceptable tradeoff, because in my experience the vast majority of FXL EPUBs apply critical styling to the `body` rather than the `html` root element. At worst, this method removes/replaces the HTML background color/image, instead of letting it bleed into the page "margins" (i.e. unused logical parts of the physical viewport).

I tried using `transform-box` and `transform-style`, to no avail. I tried using combinations of `background-clip`, `background-attachment`, etc. to no avail. I also tried to migrate the scale+translate transform from `html` to `body` ... to no avail.

I will uploads a series of screenshots in my follow-up posts...

**Comment by danielweck** [comment] 2021-08-17 10:11
To visualise the top-level containers which have `overflow: hidden`, I added a blue dotted border on `body`, and a red outline on `html`. The silver/grey background color is on the `body`, but the CSS transform make it "bleed" across the entire viewport:

<img width="1043" alt="Screenshot 2021-08-17 at 09 58 50" src="https://user-images.githubusercontent.com/625201/129707652-1c13be3d-26cd-41a9-92e7-8bc80b286d53.png">

**Comment by danielweck** [comment] 2021-08-17 10:12
Using the "1px transparent background image" trick, the "bleeding background" issue disappears:

<img width="1043" alt="Screenshot 2021-08-17 at 10 01 28" src="https://user-images.githubusercontent.com/625201/129707932-4458e5c4-1f8a-437e-9c93-a3a0e05b6ef8.png">

**Comment by danielweck** [comment] 2021-08-17 10:15
...but, if the HTML root element itself has a background color (here in this example, red), then we must make sure to `unset` it in our injected CSS:

<img width="1043" alt="Screenshot 2021-08-17 at 10 05 13" src="https://user-images.githubusercontent.com/625201/129708075-e042754b-ecdc-4e5f-a36b-b827d2bbf136.png">

...then we achieve the desired output:

<img width="1043" alt="Screenshot 2021-08-17 at 10 07 54" src="https://user-images.githubusercontent.com/625201/129708313-2721cf4e-a558-4dad-a8fe-75533557b121.png">

**Comment by danielweck** [comment] 2021-08-17 10:17
Here is another test where I forced an arbitrary CSS scale+translate transform, and I used a gradient background to better visualise the body background color "bleed" into the rest of the viewport (irrespective of `width`/`height` dimensions, `overflow: hidden`, and other containment rules):

<img width="1498" alt="Screenshot 2021-08-17 at 10 54 35" src="https://user-images.githubusercontent.com/625201/129708643-65d65272-7913-451a-b408-b884e4dc4925.png">

**Comment by danielweck** [comment] 2021-08-17 10:18
...things become clearer once the HTML root element has a red background color:

<img width="1454" alt="Screenshot 2021-08-17 at 10 54 46" src="https://user-images.githubusercontent.com/625201/129708767-c04ee5e1-c41a-4f49-9c33-e6f88ae1f20d.png">

**Comment by danielweck** [comment] 2021-08-17 10:19
...once we apply the full CSS workaround, we get this:

<img width="1498" alt="Screenshot 2021-08-17 at 10 55 52" src="https://user-images.githubusercontent.com/625201/129708982-306c8733-5fc6-4fb2-9822-0430ba3418dc.png">

**Comment by raxelbrof** [comment] 2021-08-17 10:59
Would you mind posting the CSS solution you used for the final result in this post?

Thnaks.

> ...then we achieve the desired output:
> 
> <img alt="Screenshot 2021-08-17 at 10 07 54" width="1043" src="https://user-images.githubusercontent.com/625201/129708313-2721cf4e-a558-4dad-a8fe-75533557b121.png">

**Comment by danielweck** [comment] 2021-08-17 14:34
The solution will be in the reading system / Thorium itself. This is a problem caused by the rendering engine (or to be precise, the way CSS transforms content in the viewport), so we cannot expect content authors to adapt their stylesheets in order to work around a particular's reading system's quirks.

**Comment by danielweck** [comment] 2021-08-25 10:49
Fixed via https://github.com/readium/r2-navigator-js/commit/5627671a38b218d04535ec3bdb7a0270daf280ac
(will be included in Thorium's upcoming release)

**Closed by danielweck** 2021-08-25 10:49 UTC
