### ISSUE TITLE
OPDS feed, no cover images, and title/author label clipping

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1347] opened 2021-01-29 11:19 UTC
"Columbia" feed (@llemeurfr knows which one):

<img width="1276" alt="Screenshot 2021-01-29 at 10 58 06" src="https://user-images.githubusercontent.com/625201/106268941-b67db080-6223-11eb-977f-f7f5d340de06.png">

**Comment by panaC** [comment] 2021-02-02 18:30
on my side 
![image](https://user-images.githubusercontent.com/3198865/106645750-101c0d00-658d-11eb-8883-847e59135d2b.png)

**Comment by panaC** [comment] 2021-02-02 18:33
i'm closing the issue, i'm quasi sure it's not a bug.

on the other hand , label clipping should be a dedicated issue in the tracker for me

**Closed by panaC** 2021-02-02 18:33 UTC
Labels: opds

**Comment by panaC** [comment] 2021-02-02 18:34
feel free to reopen it @danielweck , maybe i'm wrong

**Comment by llemeurfr** [comment] 2021-02-02 20:14
I also see the covers on my instance of Thorium Reader for this feed.

**Comment by danielweck** [comment] 2021-02-05 19:05
I tested this again, and it works now. It was a server problem, I guess.

**Comment by danielweck** [comment] 2021-02-05 19:06
Note that the overlapping title / author labels was fixed via:
https://github.com/edrlab/thorium-reader/commit/1dac736089b9cb38a21eef685b1de5b655be6c41
