### ISSUE TITLE
Wrong date in About This Book dialog

### ISSUE THREAD

**Issue by jmamcrg** [edrlab/thorium-reader#1930] opened 2023-03-18 18:39 UTC
How to correct wrong date in Thorium | About this Book | Book Details | Published on | **Date incorrect**

EPub was created in Calibre. 

![Thorium Calibre](https://user-images.githubusercontent.com/127980058/226129396-6dbee7bb-442e-4dde-977a-b15f71eb5c8e.png)

**Comment by danielweck** [comment] 2023-03-18 18:44
hello, thank you for reporting this. would you mind privately sharing the epub? ( daniel.weck@gmail.com )
alternatively, could you please copy+paste your package OPF metadata here?
thank you

**Comment by danielweck** [comment] 2024-05-16 17:38
Closing due to lack of publication to reproduce the bug

**Closed by danielweck** 2024-05-16 17:38 UTC
