### ISSUE TITLE
Windows: opening EPUB files directly from file explorer fails when other than C:/ (imports in OPDS catalog view)

### ISSUE THREAD

**Issue by wasniahC** [edrlab/thorium-reader#1620] opened 2022-01-13 09:41 UTC
Opening an epub directly from the file does not add it to the library and open the epub, as it used to. Instead it goes to the "catalogs" tab and gives the following error:

![opds error](https://user-images.githubusercontent.com/57833420/149304470-93125a2b-61dc-4603-bc39-fbf3215dbcad.png)

I believe it's trying to open the epub as an OPDS catalog by default. I can't find a way to stop it from doing this when opening directly from the file.

I can work around it by manually adding epub to the "My Books" section and opening it from that menu - this issue occurs only when trying to directly open an epub file from file explorer when epubs are associated with thorium.

**Comment by danielweck** [comment] 2022-01-13 12:20
Hello, this sounds like a regression introduced via https://github.com/edrlab/thorium-reader/pull/1573

@panaC I am going to run tests again, can you please check at your end (you will be quicker than me to analyse the PR code logic)

**Comment by danielweck** [comment] 2022-01-13 12:28
I have just finished testing on MacOS from a clean slate (empty Thorium bookshelf), using a matrix of possible scenarios:
* app already opened (library window), vs. app completely closed.
* at least one reader window open, vs. none open.
* publication already imported, vs. publication not in bookshelf yet.

I am unable to reproduce the bug. I will test on my Windows virtual machine.

**Comment by wasniahC** [comment] 2022-01-13 12:40
For avoidance of doubt, I've tried restarting PC and reinstalling thorium through the windows store. The version installed this morning is v1.8.0 - and I only noticed this issue starting yesterday (worked fine for me last time I opened something in it before then, maybe a week ago? unsure)

I've just tried combinations of the above troubleshooting steps to be sure, and this issue occurs for me in all of the above scenarios if it isn't being added manually to the library and then opened from the library.

**Comment by danielweck** [comment] 2022-01-13 13:26
Ah, the bug is that this feature only works with `C:/`
@panaC was that intentional?

**Comment by panaC** [comment] 2022-01-13 14:25
Thanks, it's a regression bug.
This will be fixed soon.

Note for me:
https://github.com/validatorjs/validator.js/blob/master/src/lib/isURL.js

**Comment by danielweck** [comment] 2022-02-04 10:01
Same issue (duplicate): https://github.com/edrlab/thorium-reader/issues/1632

**Comment by PhilippeBruno** [comment] 2022-02-04 10:05
When is the fix going to be available? Do I have to downgrade to 1.7.0?

**Closed** 2022-02-04 10:05 UTC

**Comment by danielweck** [comment] 2022-02-04 10:07
Hello @PhilippeBruno the bugfix will be available shortly in the automated build of Thorium (alpha test release). We would really appreciate if you could test at your end to confirm that the fix works! :)
See: https://github.com/edrlab/thorium-reader/actions/runs/1794328784

**Comment by danielweck** [comment] 2022-02-04 10:22
The test build is available :)

**Comment by PhilippeBruno** [comment] 2022-02-04 10:32
> 

I know, I already tested it!

It works well now. It opens any EPUB by double clicking on them in Windows File Explorer.

One question and one comment:

Q1: Is this the new way Thorium works now with the main window staying open and the EPUB opening in a new window on top?

C1: The uninstall of v1.8.0 was not complete. It left a folder in "C:\Users\\%UserName%\AppData\Local\Programs" and a bunch of files in "C:\Users\\%UserName%\AppData\Roaming\EDRLab.ThoriumReader"

**Comment by danielweck** [comment] 2022-02-04 11:26
> Q1: Is this the new way Thorium works now with the main window staying open and the EPUB opening in a new window on top?

Discussion: https://github.com/edrlab/thorium-reader/issues/1632#issuecomment-1029897134

(sorry about the cross-threading)

**Comment by danielweck** [comment] 2022-02-04 11:28
> C1: The uninstall of v1.8.0 was not complete. It left a folder in "C:\Users\%UserName%\AppData\Local\Programs" and a bunch of files in "C:\Users\%UserName%\AppData\Roaming\EDRLab.ThoriumReader"

Was that with Thorium installed from the Windows Store, or via the standalone `.exe` installer?

Note that it is important that these files remain in place, otherwise any uninstall + re-installation of Thorium would result in loss of user data (i.e. bookshelf, settings, bookmarks, etc.)

**Comment by PhilippeBruno** [comment] 2022-02-04 12:12
> Was that with Thorium installed from the Windows Store, or via the standalone `.exe` installer?

I believe the Windows Store is still at version 1.7.0. In my case, it was from the standalone ".exe" installer.
 
> Note that it is important that these files remain in place, otherwise any uninstall + re-installation of Thorium would result in loss of user data (i.e. bookshelf, settings, bookmarks, etc.)

Well, I am not sure I agree completely with this behaviour. For an application like Word or PowerPoint that lets users decide where to save files, even if it suggests a "My Documents" folder, it would be a catastrophe if upon uninstalling the application, all the user created files would be gone. However, for an application like Thorium that creates a database of EPUBs in an obscur folder duplicating EPUBs already on the user's computer somewhere (keep in mind I manage my files in my own directory structure--scientific articles, ebooks, etc.--according to my various projects). As such, I could not care less for the Thorium database file that's being created, so I expect this folder to disappear, or at least have the option to delete it, when I uninstall the application. On a side note, I still delete from Thorium all the EPUBs I open every week to reclaim the space wasted by the import process. Some weeks, it reaches close to 500MB! Anyway, I long stopped hoping for a better handling of EPUBs that would allow me to bypass the import completely...
