### ISSUE TITLE
v1.6 on Ubuntu 20.04 LTS, issue with PDF

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1441] opened 2021-04-23 12:48 UTC
"Release 1.6 tested on Linux Ubuntu 20.04 LTS : if ePub format works pretty well (ePub 3 Fixed Layout included !), curiously PDF no… I’ve tried with some PDFs but no way 🙁"

**Comment by danielweck** [comment] 2021-05-19 08:55
Can this be verified on 1.7, please?

**Comment by danielweck** [comment] 2021-05-19 09:45
Cannot reproduce, closing.

**Closed by danielweck** 2021-05-19 09:45 UTC
