### ISSUE TITLE
Mac Thorium 1.7 Improper File Type association in info.plist

### ISSUE THREAD

**Issue by raxelbrof** [edrlab/thorium-reader#1473] opened 2021-05-24 09:08 UTC
Hi,

Feedback request: Please remove the claim of .opf files from Thorium's info.plist

.opf is not a file any user should be interacting with, so there is no purpose in it being a clickable launcher of Thorium. Currently installing / using 1.7 is assigning Thorium's icon to all of them.

Even if we get-info on the file and manually associate it with a text editor, and associate all .opf files with our chosen editor, the Thorium icon sticks around in Finder, and any app showing a file listing, requiring a Launch Services Database rebuild to clear it out.

1.6 did not claim .opf as a file type for itself, it would be better if 1.7 onwards didn't, either.

**edit:** Worse still, the icon Thorium uses, is the _application's_ icon, not a Thorium-specific _Document Icon_. That's a pretty fundamental thing - files openable by an app, should not have the same icon as the app itself. But that said, Thorium should not be claiming file types that are not proprietary to Thorium itself.

Thanks.

**Comment by danielweck** [comment] 2021-06-07 18:01
Related issues:

https://github.com/edrlab/thorium-reader/issues/1474#issuecomment-856146128

https://github.com/edrlab/thorium-reader/issues/1468#issuecomment-856139158

**Comment by danielweck** [comment] 2021-06-07 18:03
> `.opf` is not a file any user should be interacting with

Thank you for your feedback. DAISY3 Digital Talking Books can be opened from ZIP container files, as well as from OPF package XML of exploded / unzipped file sets.

I am closing this issue as a duplicate of the aforementioned one. I will copy you message across, thank you! 👍

**Closed by danielweck** 2021-06-07 18:03 UTC
