### ISSUE TITLE
Focus shifts automatically to book content when opening or closing Settings using the Left or Right View options using a screen reader

### ISSUE THREAD

**Issue by togregg** [edrlab/thorium-reader#2607] opened 2024-10-11 18:29 UTC
### Impact: Minor
[WCAG 2.1 SC 3.2.1: On Focus (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html)

### Current Behavior:
With the left or right view enabled from book settings, when a screen reader user activates the settings button in a book, focus automatically goes back into the book. You must navigate back to the Settings button in the interface to navigate the settings options. Additionally, when you close the Settings button, focus goes into the book automatically.

### Example:
Using VoiceOver navigate to the Settings button and then activate it. The options for settings will appear visually on the right side of the interface and then focus will jump back into the book.

### Expected Behavior:
With the left or right view enabled from book settings, when a screen reader user activates the settings button in a book, focus stays on the Settings button.

#### Windows
- Windows 11 Pro Version 22H2 OS build 22621.3447
- JAWS 2024.2409.2
- NVDA 2024.1 (2024.1.0.31547)
- Thorium v3.0.0

#### macOS
- Sonoma 14.7 (23H124)
- Voice Over for Sonoma
- Thorium 3.0.0

### Steps to recreate:

1. Have your screen reader of choice running.
2. Launch Thorium.
3. Open a Book.
4. Using standard keyboard navigation commands for a screen reader, go the settings button and activate it.\
   - JAWS/NVDA – Down arrow
   - VoiceOver – Ctrl + Option + Right Arrow

5. From the display dialogue, move up to put focus on the Display Tab and then press Tab twice.
6. You will be on the left button, now navigate to the right button and activate it.
7. The display options are now docked to the right side of the book window and focus is on the book text.
8. Navigate back to the Settings button and activate it.
9. The settings options on the right side go away and focus goes back into the book.  

### Video(s)/Screenshots:
[Video - - Focus shifts automatically to book content when opening or closing Settings using the Left or Right View options](https://iu.mediaspace.kaltura.com/media/t/1_r39e2vpl)

### Recommendations:

- Maintain focus on the Settings button when opening or closing it.

**Comment by danielweck** [comment] 2024-11-05 11:00
This is a known issue in Thorium but thank you for reporting details. Since Thorium version 3, some React user interface libraries were integrated to improve visuals and ergonomics, but this also introduced a number of keyboard focus issues / inconsistencies. We are working on diagnosing and fixing these regressions.

**Comment by togregg** [comment] 2024-11-12 20:02
@danielweck Thanks for the update. The issue also occurs when trying to change the font size just using the keyboard (and no screen reader). It does not matter which view you use, the loss of focus issue occurs.

**Comment by danielweck** [comment] 2024-11-13 21:10
closing as duplicate: https://github.com/edrlab/thorium-reader/issues/2379

**Closed by danielweck** 2024-11-13 21:10 UTC
