### ISSUE TITLE
Error: Import failed for the publication path

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1315] opened 2021-01-14 16:13 UTC
Received by email. 

When I try to open an Epub with Thorium Reader, I get this error message:

"Import Failed"
Error: Import failed for the publication path:  (shows path to file on my PC)

Would you have any suggestions for fixing this.

I currently work for... as an Accessibility Tester.  I use it for my work all the time.  It's a great application and I hope I can continue to use it for my work and leisure reading.

**Comment by danielweck** [comment] 2021-01-14 16:31
I am afraid this is issue is not actionable if we do not have a test publication to attempt to reproduce the bug with. Also, we would need to know the platform (Windows, MacOS, Linux), and Thorium version number / release date.
I propose we close this issue if no further information is received within a week or so.

**Comment by danielweck** [comment] 2021-01-14 16:38
I suspect the logic has changed since the last official release (v1.5):
https://github.com/edrlab/thorium-reader/blob/afab8bb287b71cb43b849b19f2213fe679a6d7de/src/main/cli/process.ts#L240-L250

**Comment by llemeurfr** [comment] 2021-01-14 16:48
Yes, it happens with any Epub  I try to import.  I doesn’t make any difference how I import it…double click, drag and drop.
 It is version 1.5.0.
 My operating system is Windows 10 Home,  version  10.0.19042, Build 10042

**Comment by danielweck** [comment] 2021-01-14 17:10
Could the user please try with v1.6 "alpha" builds:
https://github.com/edrlab/thorium-reader/releases

**Comment by llemeurfr** [comment] 2021-01-15 09:35
v1.6 alpha Works for the user but let's be careful it does not use the same database. Maybe some disk limit reached?

**Comment by panaC** [comment] 2021-01-15 11:07
Possible indeed

**Comment by danielweck** [comment] 2021-05-19 09:30
Thorium 1.7 was released, this bug report was for 1.5. Closing due to lack of information / reproducibilty.

**Closed by danielweck** 2021-05-19 09:30 UTC
Labels: in pending, invalid, question
