### ISSUE TITLE
Footnotes will not display properly if they are in an HTML file that is different from the text

### ISSUE THREAD

**Issue by 1204244136** [edrlab/thorium-reader#1606] opened 2021-12-18 05:46 UTC
Comments pop up when footnotes and body are in the same HTML file
comments jump when footnotes and body are in different HTML files

**Comment by danielweck** [comment] 2021-12-18 11:06
Hello, this is correct, it is the intended behaviour (it is a feature, not a bug).
Thorium does not fetch the contents of other publication HTML files as this would break CSS styling when presenting the DOM fragment of the popup footnote in the current document. Other reading systems present basic textual information but Thorium renders actual HTML markup with applied user-configured formatting as well as some authored styles.

**Comment by danielweck** [comment] 2021-12-18 11:09
I am going to close this "feature request" for now, as we have no plans to implement "remote" popup footnotes (only local ones). Feel free to re-open or comment further, as we monitor the issue tracker and we would be happy to discuss this more if necessary, thanks! :)

**Comment by 1204244136** [comment] 2021-12-19 07:33
> Comments pop up when footnotes and body are in the same HTML file comments jump when footnotes and body are in different HTML files

For the latter,I mean although the footnotes and body are in different HTML files,they are in the same ePub files.They are all local.
I found this problem because recently I want to put all the footnotes that are scattered in different HTML files in the same new HTML file and then I noticed that the comment jumped instead of popping up(all of this is done on a local ePub file and each HTML file uses the same CSS file).

**Comment by danielweck** [comment] 2021-12-24 18:18
Hello, I fixed a few issues with EPUB popup footnotes (bottom alignment of the modal dialog, auto-hiding of same-document targeted notes content). I also implemented support for external documents. I am attaching a test file to this post, feel free to give it a try (I only tested on Mac so I am interested in getting feedback from Windows and Linux ... though I am 99.9% sure that it should work cross-platform :)

Would you mind testing with your own EPUB as well? Are you able to share it here?

[footnotes_sub-folder.zip](https://github.com/edrlab/thorium-reader/files/7774984/footnotes_sub-folder.zip)

I will post another message shortly to announce the Thorium build.

**Closed** 2021-12-24 18:19 UTC

**Comment by danielweck** [comment] 2021-12-24 18:21
Fixed via: https://github.com/edrlab/thorium-reader/commit/8f5bcedf1ea091a4e153dee711ec1307959799b3
...or more specifically, via: https://github.com/readium/r2-navigator-js/blob/develop/CHANGELOG.md#1910
(code diff: https://github.com/readium/r2-navigator-js/compare/v1.9.9...v1.9.10 )

Thorium is now being compiled (test builds):
https://github.com/edrlab/thorium-reader/runs/4628394539

**Comment by 413Michele** [comment] 2022-02-09 14:59
I'm sorry to say that while your test file opens the notes correctly, the 4 tests I made with real world EPUB files with notes in different HTML files (typically at the end of the book) all failed: clicking on the link sent me to the notes file.

My books are mostly copyrighted, I'll try to find a problematic public domain one that I can post here. Otherwise, I could send my files privately

**Comment by danielweck** [comment] 2022-02-09 15:30
thank you for your feedback. feel free to send me a private email, I regularly obtain confidential epubs for testing.
