### ISSUE TITLE
Embedded fonts cause vertical scrollbar in paginated mode

### ISSUE THREAD

**Issue by Simon-Collinson** [edrlab/thorium-reader#1535] opened 2021-08-31 00:38 UTC
We are testing some EPUBs in Thorium and have noticed a strange behaviour with some embedded fonts in paginated mode. 

At certain font sizes and line spacing settings, the block content area seems to be marginally taller than the allocated vertical space, resulting in a scrollbar:
![image](https://user-images.githubusercontent.com/8330542/131422579-5024606d-b1bc-4c07-aeb1-416520c77329.png)

This does not occur when the user switches to an included font. It also seems to prevent the text from breaking across the column:
![image](https://user-images.githubusercontent.com/8330542/131422967-35650881-f449-4946-bd11-a70e0655a8fd.png)

Our colleague [Arthur](https://github.com/arthurattwell) has experimented and believes the problem may be related to users changing line spacing settings. Please let me know if you need a minimal working example or further info.

**Comment by danielweck** [comment] 2021-08-31 06:44
hello, yes please I would need an epub that exhibits this behaviour, and I will happily investigate '

**Comment by Simon-Collinson** [comment] 2021-08-31 22:27
Thanks, @danielweck - please see attached.
[heart-of-darkness.zip](https://github.com/edrlab/thorium-reader/files/7087093/heart-of-darkness.zip)

**Comment by danielweck** [comment] 2021-09-08 18:25
Very strange indeed! I am able to reproduce this easily. Looks like a web browser quirks. The problem disappears when setting CSS `overflow: hidden` on the `body` element, a technique which does not seem to introduce any negative side effects. I tested with paginated and scroll modes, as well as fixed layout documents, for good measure (as the CSS is applied for all types of publications alongside `position: relative` which is used to reset the coordinates reference frame for when drawing annotations / highlights)

**Comment by danielweck** [comment] 2021-09-08 18:37
Fixed via https://github.com/edrlab/thorium-reader/commit/1affa7a613532cfc7d1da2d5901d77850600eed0

**Comment by Simon-Collinson** [comment] 2021-09-08 18:53
Thanks for the info and the fix, @danielweck!

**Comment by danielweck** [comment] 2022-03-04 12:17
> The problem disappears when setting CSS `overflow: hidden` on the body element, a technique which does not seem to introduce any negative side effects.

Unfortunately we found an reflowable EPUB that breaks because of this :(
(some CSS quirks it seems, I am not able to pin-point a style that would trigger this edge case in the cascade)

![css-is-awesome](https://user-images.githubusercontent.com/625201/156762012-4e70c803-6307-46c3-b467-476b28605606.jpg)

**Comment by danielweck** [comment] 2022-03-04 14:59
Fixed via https://github.com/edrlab/thorium-reader/commit/3d44c1609e65f9559a25df63e5b8938da5faea75
(see https://github.com/readium/r2-navigator-js/commit/07a8c64febe46afe1fc71892955b2d422780eb26 )

**Closed by danielweck** 2022-03-04 14:59 UTC
