### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1432] opened 2021-04-08 13:11 UTC
While trying to open an EPUB, I got the following error:

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: One-time callback was called more than once
  at failure

![Thorium_F4dpsjY5Ug](https://user-images.githubusercontent.com/36426806/114032375-40608000-984a-11eb-962e-3683042df91b.jpg)

Problematic EPUB emailed privately to Daniel Weck.

**Comment by panaC** [comment] 2021-04-08 16:22
Thanks to report this 👍 

but it's a duplicate of #1327 
i'm closing the issue.

**Closed by panaC** 2021-04-08 16:22 UTC

**Comment by PhilippeBruno** [comment] 2021-04-08 16:26
Sorry Pierre, but I beg to differ. The symptoms (error message) may be the same, but in this case, the actions leading to the problem are not the same. As soon as I open the EPUB, without attempting to search anything in the book, I get the error message.

**Comment by panaC** [comment] 2021-04-08 16:33
I see but can you report it on #1327 too . It's probably the same issue .. I guess :)

**Comment by danielweck** [comment] 2021-04-09 14:58
@PhilippeBruno thank you for sharing a test EPUB. Unfortunately I am not able to reproduce the bug, although I must admit not having tried on my older Windows computer yet.

@panaC I agree with Phillippe that we should not immediately assume that because the error message is similar to other bug reports, the cause is related. In the Thorium project have now seen several instances of this obscure Electron / NodeJS "callback called more than once" error, but with totally different interaction paths in the Thorium UI.

In fact, in another project I have experienced similar confusion, and in the end the problem was in fact traced down to some unhandled promise rejection due to corrupted filesystem access. Very hard to reproduce consistently, and to troubleshoot.

So, I will leave this issue closed for now, and we shall continue to explore this problem in #1327 . Hopefully we will be able to determine a more targeted explanation of the problem(s), and we will then file new issues with a more actionable scope.
