### ISSUE TITLE
[Feature Request] Printing

### ISSUE THREAD

**Issue by Francois059** [edrlab/thorium-reader#1633] opened 2022-02-03 15:10 UTC
Being able to print from Thorium would be very useful. Adobe Digital Editions includes printing but it does not work under Windows 10/11 and works fine under macOS Monterey. Still looking for the “best” ePUB reader. Apologies if a similar request has already being submitted in a previous post.

**Comment by llemeurfr** [comment] 2022-02-03 16:54
duplicate of #895

**Closed by llemeurfr** 2022-02-03 16:54 UTC
