### ISSUE TITLE
Windows: admin vs. regular users, filesystem permission crash at startup (EDRLab.ThoriumReader folder user access control?)

### ISSUE THREAD

**Issue by preevi-singh** [edrlab/thorium-reader#1514] opened 2021-06-17 04:06 UTC
thorium is not compatible with windows 21H1 version. and I am using latest version 1.7.00  it always shows java script error although I have downloaded it from microsoft store.  I would be glad to see hindi language included in the further update.

**Comment by llemeurfr** [comment] 2021-06-17 17:04
Hi @preevi-singh, I'm surprised by the windows 21H1 issue you're raising, we'll check on our side. Can you please detail what happens, and did you install the June Patch Tuesday? (the initial release was buggy I heard).  

Re. the Hindi language, translations are community based. Volunteers maintain the translation of a json document in each supported language. We'll first check if there could be technical issues with Hindi. If being in charge of the Hindi translation would be ok for you, we'll then be able to organize that with you.

**Comment by preevi-singh** [comment] 2021-06-18 04:18
thorium shows the system cannot find the file specified. exit code 1.
I have installed ver 1.7.0.0 on microsoft store it shows it was
released on may 2021

**Comment by preevi-singh** [comment] 2021-06-18 05:32
> thorium is not compatible with windows 21H1 version. and I am using latest version 1.7.00 it always shows java script error although I have downloaded it from microsoft store. I would be glad to see hindi language included in the further update.

> ¦
•*>
• /C .
"¦1: *

' X

© Error
* Application init Error

main rootSaga: OpenError: IO error: C:\Users\PREEVI
SINGH\AppData\Roaming\EDRLab.ThoriumReader\db\lcp-secret/MANIFEST-000020: The system cannot find the file specified.

zX T CODE

tro Pane

**Comment by preevi-singh** [comment] 2021-06-18 05:32
code was 01

**Comment by llemeurfr** [comment] 2021-06-18 13:26
Hi Preevi, did you close this issue by mistake? your last comment is cryptic.

**Comment by danielweck** [comment] 2021-06-18 13:28
Hello, I am building Thorium on a recently-updated Windows machine. I will report back with my findings once I have finished running tests with a conventional app installer, as well as with a Windows Store deployment.

**Comment by danielweck** [comment] 2021-06-18 13:30
I am unable to reproduce the reported bug with Windows 10 20H2 and Thorium 1.7.0 (I will publish 1.7.1 soon to the Windows Store ... work in progress)

**Comment by danielweck** [comment] 2021-06-18 13:36
I am installing Windows 10 Pro update 21H1 ...

**Comment by danielweck** [comment] 2021-06-18 14:03
I uninstalled Thorium 1.7, re-installed the app via the Windows Store, and I tried running the app with both previous / existing settings located in `C:\Users\daniel\AppData\Roaming\EDRLab.ThoriumReader\` and fresh new settings in `C:\Users\daniel\AppData\Local\Packages\EDRLab.ThoriumReader_xxxx\LocalCache\Roaming\EDRLab.ThoriumReader\`.

=> No crash, everything seems to work fine.

**Comment by preevi-singh** [comment] 2021-06-18 14:07
But it is not working at my end..

**Comment by danielweck** [comment] 2021-06-18 14:10
Suggestion: rename your folder `C:\Users\PREEVISINGH\AppData\Roaming\EDRLab.ThoriumReader` (for example, add a character at the end of the folder name), and launch Thorium again.

**Comment by llemeurfr** [comment] 2021-06-18 14:16
Looking a the path given in the error, `C:\Users\PREEVI SINGH\AppData\Roaming\EDRLab.ThoriumReader\db\lcp-secret/MANIFEST-000020`, I do not understand your suggestion Daniel.

**Comment by danielweck** [comment] 2021-06-18 14:18
This is a process of elimination: when Thorium starts "from scratch", the Electron framework will generate an app-specific folder in either `C:\Users\XX\AppData\Roaming\EDRLab.ThoriumReader\` or `C:\Users\XX\AppData\Local\Packages\EDRLab.ThoriumReader_xxxx\LocalCache\Roaming\EDRLab.ThoriumReader\`.

**Comment by llemeurfr** [comment] 2021-06-18 14:20
ah ok you mean rename the folder to something else ...

**Comment by llemeurfr** [comment] 2021-06-18 14:29
To improve the app we need your assistance. Could you please rename temporarily this folder so that we can check what happens?

**Comment by preevi-singh** [comment] 2021-06-18 14:38
How to do so?

**Comment by llemeurfr** [comment] 2021-06-18 14:47
the detail of the answer depends on your technical expertise. Are you a developer, and advanced windows user or casual windows user?

**Comment by preevi-singh** [comment] 2021-06-18 14:56
Casual

**Comment by llemeurfr** [comment] 2021-06-18 14:58
If you are a casual Windows user: 

- close Thorium
- open a terminal
- type "ren C:\Users\PREEVI SINGH\AppData\Roaming\EDRLab.ThoriumReader EDRLab.ThoriumReader1"
- check if the command is accepted
- launch Thorium and advise. The bookshelf should be empty but no ebook is lost.

**Comment by danielweck** [comment] 2021-06-18 15:05
> improve the app so that a normal person can install it easily in any folder where he/she wants to and can use it easily.

Hello, you can install Thorium from the Windows Store or from a regular installer (`Thorium.Setup.1.7.1.exe`):
https://github.com/edrlab/thorium-reader/releases/tag/v1.7.1

Windows OS traditionally uses the "C:/Program Files" folder, but for some apps the installation folder is `C:\Users\XX\AppData\Roaming\Programs\EDRLab.ThoriumReader\` (if I remember correctly)

**Comment by danielweck** [comment] 2021-06-18 15:06
> type "ren C:\Users\PREEVI SINGH\AppData\Roaming\EDRLab.ThoriumReader EDRLab.ThoriumReader1"

This is unlikely to work because of the space character in `PREEVI SINGH`

**Comment by danielweck** [comment] 2021-06-18 15:07
> How to do so?

You can use the file explorer to go to your `C:\Users\PREEVISINGH\AppData\Roaming\EDRLab.ThoriumReader` folder, but note that the `AppData` subfolder is in fact hidden, so you may have to make sure that file explorer displays hidden files.

**Comment by danielweck** [comment] 2021-07-23 15:16
similar error message in this project:
https://github.com/storj/storjshare-gui/issues/675

**Comment by danielweck** [comment] 2021-07-23 15:18
another similar error message:
https://github.com/Level/levelup/issues/222

**Comment by llemeurfr** [comment] 2021-07-23 15:19
Similar warning from another user, this time with a screenshot: 

![image](https://user-images.githubusercontent.com/14943186/126803540-db478847-9a45-4aa5-9f05-cc8eea9e0f1e.png)

Version 1.7.1 downloaded directly from the repository.

"I click download and am able to start installing. Then when the installation is supposed to be finished, I receive the following message ..."

**Comment by danielweck** [comment] 2021-07-23 15:21
So, it looks like a LevelDB / LevelDown error, judging by the filepath (the keyword "MANIFEST-xxx" is a clue too).

**Comment by danielweck** [comment] 2021-07-23 15:22
Filesystem permission problem?
Concurrent process IO access?

**Comment by llemeurfr** [comment] 2021-07-23 16:09
Some details: 

- is it the same message you've seen initially (what you called "notification that a virus was stopped from the download") ? 

I use McAfee virus protection, and after I receive the screenshot notification, I receive another notification from McAfee indicating that a virus was stopped from downloading. 

- did you use a previous version of Thorium before, and which one? 

Yes I did! I used the last version of Thorium that was available in February 2021 (not sure the version number). I had no issues with this until a Windows update occurred and then I was not able to open Thorium at all. That was when I tried to download the latest version, 1.7.1.

- did you update your Windows system to the latest version lately (named 21H1 in the litterature)? it seems that the issue could be tied to an update of Windows (but with the new version we still cannot reproduce).  

Yes, an automatic update from Windows happened last week which is when my Thorium stopped working.

- if we recommend that you delete the database of ebooks which is handled by Thorium, will it be an issue for you?

I'm not sure what this means. Currently, I have completely deleted and uninstalled the last version of Thorium that I had, hoping it would help the new installation.

**Comment by danielweck** [comment] 2021-12-03 18:00
Closing due to lack of feedback / activity. Feel free to reopen if the bug re-occurs! Thank you :)

**Comment by danielweck** [comment] 2022-03-28 12:17
The problem still occurs, it seems:
![image001](https://user-images.githubusercontent.com/625201/160395941-4ddb6c03-8054-4a04-82a6-bb79f12d6cee.jpg)

**Comment by danielweck** [comment] 2022-03-28 12:28
In the screenshots below I highlighted the text that Thorium programmatically inserts (all other text is generated by Windows OS or some underlying software library outside of our control, text which we obtain from the captured error / exception message):

![image001](https://user-images.githubusercontent.com/625201/160397627-8715b016-ae70-4826-9ace-a6ebe04c04ae.jpg)
![126803540-db478847-9a45-4aa5-9f05-cc8eea9e0f1e](https://user-images.githubusercontent.com/625201/160397637-82642a55-b419-4e13-8386-096da374124e.png)

**Comment by danielweck** [comment] 2022-08-26 19:05
Closing due to lack of activity, issue not actionable as unidentified problem. Clearly if the problem continues to be reported we will record the feedback but this is impossible to fix without a reproducible pattern, and this may in fact not be fixable at all in Thorium (Electron + Windows issue)

**Closed by danielweck** 2022-08-26 19:05 UTC
