### ISSUE TITLE
What does "OPDS feed" mean?

### ISSUE THREAD

**Issue by spudthebud** [edrlab/thorium-reader#1632] opened 2022-02-02 13:42 UTC
I encountered a problem while opening an ePub.  While trying to figure it out,  I noticed the interface refers to "OPDS feed". I don't know what that means. Could <abbr> tag be used , or some other form of help?

![image](https://user-images.githubusercontent.com/8799391/152164605-5acee5ba-3961-44bb-821a-54bcc0501402.png)

And it also appears elsewhere:

![image](https://user-images.githubusercontent.com/8799391/152164302-9cc18e75-bc07-4f50-b4dd-951c0611dd03.png)

**Comment by PhilippeBruno** [comment] 2022-02-04 09:45
Same exact problem here. Quite annoying. I have to drag and drop and EPUB onto the main window to open it.

**Comment by danielweck** [comment] 2022-02-04 10:00
I am not able to reproduce this bug (MacOS), does this occur when double-clicking on an EPUB file from the filesystem explorer (or using the "open with" context menu), or when using the "+" button from Thorium's graphical user interface to open a publication via the file chooser, or when using drag-and-drop?

I suspect this is a duplicate of this issue, which has been solved but the bugfix has not been released yet:
https://github.com/edrlab/thorium-reader/issues/1620
Closing for now, I will update the original issue.

**Closed by danielweck** 2022-02-04 10:00 UTC

**Comment by PhilippeBruno** [comment] 2022-02-04 10:03
Absolutely. We cannot open EPUBs by double clicking them in Windows File Explorer!

**Comment by danielweck** [comment] 2022-02-04 10:03
@spudthebud @PhilippeBruno could you please confirm that this is happening from a Windows drive other than `C:`? If so, then this is the same issue which now has a fix. If not, it is a different problem and I will re-open this issue.

**Comment by PhilippeBruno** [comment] 2022-02-04 10:10
@danielweck If I copy the EPUB into C:\ on my machine, I can open it by double clicking it. Otherwise, in any other folder, it returns the error message above.

Also, note that when I open the EPUB from C:\, while it does open in Thorium, there is no button to return to the main screen. I am not sure if this is a new feature to avoid building a database of EPUBs or a bug.

**Comment by danielweck** [comment] 2022-02-04 11:20
> Also, note that when I open the EPUB from C:, while it does open in Thorium, there is no button to return to the main screen. I am not sure if this is a new feature to avoid building a database of EPUBs or a bug.

The library window is in fact hidden behind the reader window. The "back" button in the top-left corner of the reader window is only displayed when the library window is not active at all, which is typically the case when opening a single publication from the bookshelf. @panaC would it be possible to completely hide the library view when double-clicking on a supported file format from the Windows file explorer / MacOS Finder, assuming Thorium launches from scratch (i.e. no existing application window)?

**Comment by PhilippeBruno** [comment] 2022-02-04 11:58
> The library window is in fact hidden behind the reader window...

Got it, thank you.

**Comment by spudthebud** [comment] 2022-02-04 12:18
@danielweck I confirm that the error message happens when I try to open an ePub file from the D: drive

**Comment by PhilippeBruno** [comment] 2022-02-04 12:20
@spudthebud Try the latest build (Thorium.Setup.2.0.0-alpha.1.1794328784) as it solves the issue.

**Comment by PhilippeBruno** [comment] 2022-02-04 12:44
> The library window is in fact hidden behind the reader window.

It is not good. It forces users to close two windows when done reading the EPUB. If one reads one EPUB per night, I guess it is acceptable. But when you open hundreds of EPUBs a day, two hundred clicks instead of one hundred clicks make a huge difference! Even my mouse battery would last only half the time! 😜

**Comment by spudthebud** [comment] 2022-02-04 13:08
@PhilippeBruno how do I know the build I have? I can that I have version 1.8 but not sure about the build number

**Comment by PhilippeBruno** [comment] 2022-02-04 13:13
Well, the V2.0.0-alpha.1.1794328784 solves the issue, but it is a version still in development (it might be unstable), so unless you are comfortable with alpha and beta testing, you should stick to version 1.8.0 which is the last official stable version (with the exception of that nuisance you and I both encountered).

From the main Thorium screen, towards the bottom of the window, you should see "About Thorium" with the version number under...

<img width="526" alt="image" src="https://user-images.githubusercontent.com/36426806/152534993-ac61b7ef-e1b5-44d4-b2f1-1928b45cacf4.png">
