### ISSUE TITLE
Display blocked on scroll mode with MathJax enabled

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#1490] opened 2021-05-28 10:43 UTC
Lorsque `MathJax` est activé il est impossible de se mettre en mode `Paginé`.

**Comment by danielweck** [comment] 2021-06-04 13:05
Hello, I am afraid this is a feature, not a bug. What I mean is that Thorium intentionally disables CSS-column pagination, due to display problems with MathJax's popup menu (i.e. MathJax's own user interface), which interfere significantly with Thorium's own document focus management. The MathJax menu is still problematic in scroll view (i.e. scroll jittering / focus jumps), but to a lesser extent compared with paginated mode.
Thank you for reporting this issue. I am closing it now as we are generally already aware that MathJax support can be improved, and we cannot safely activate pagination in the current implementation state.

**Closed by danielweck** 2021-06-04 13:05 UTC
