### ISSUE TITLE
Bug: Flash of content when navigating back to empty pages

### ISSUE THREAD

**Issue by hdmjack** [edrlab/thorium-reader#1902] opened 2022-12-23 20:43 UTC
OS: confirmed on macOS 12.5 and Windows 11

When using the app in one column mode with paginated layout, if the section is formatted in such a way that the last page is empty  pressing the back button will show a flash of content before showing the empty page, which is disorienting. 

https://user-images.githubusercontent.com/960861/209403933-93a1bbc3-d428-4286-81cf-81a9fd5bc884.mov

**Comment by seaspeak** [comment] 2023-01-28 07:50
version: v2.3.0-alpha
I noticed a similar problem. If you navigate back one page from the very beginning of a chapter, which means you will go to the last page of the previous chapter, Thorium will jump to the first page of the previous chapter, and then jump back to the last page.

**Comment by danielweck** [comment] 2023-03-01 19:10
@seaspeak this is a known behaviour, unfortunately in paginated mode (which under the hood relies on CSS columns) the document is laid out first so that the number of pages / CSS columns is determined, then the HTML anchor point is scrolled / focussed to. The current workaround is to temporarily hide the content viewport in order to give the webview renderer some time to perform the page alignment, but it seems that in some cases the delay is not sufficiently long.

**Comment by danielweck** [comment] 2023-03-01 19:12
@hdmjack Thank you for reporting this. I am not able to reproduce this problem using my own EPUBs, could you please privately share yours? ( daniel.weck@gmail.com )

**Comment by danielweck** [comment] 2024-05-16 17:40
closing due to lack of publication to test with and reproduce the bug

**Closed by danielweck** 2024-05-16 17:40 UTC
