### ISSUE TITLE
top to bottom, RTL page-progression-direction (Japanese)

### ISSUE THREAD

**Issue by toshiakikoike** [edrlab/thorium-reader#959] opened 2020-02-19 07:28 UTC
When open the EPUB, page-progression-direction="rtl", page-progression is top to bottom.
Or skip to the head of spine items.

Please watch this gif.

<img src="https://github.com/toshiakikoike/epub_file/blob/master/thorium-rtl-epub.gif?raw=true"/>

00:00-00:01 Display Setting
-- Layout: Pagenated
-- Alignment: Justify
-- Columns: 1 col
00:03-00:25 Click the "Left" button, then skip to the head of spine items.
00:26- Click the "Left" button, then page-progression is top to bottom.

Test file:
https://github.com/toshiakikoike/epub_file/blob/master/mymedia.epub

About Thorium:
Develop Branch, Feb.18/2020
v1.1.2-alpha.1

Environment:
GNU/Linux(Ubuntu 16.04 LTS)

Related #327

**Comment by JayPanoz** [comment] 2020-02-19 21:35
@danielweck from the ReadiumCSS’s P.O.V. this seems to be working OK for fragmentation as we’re relying on columns, and we don’t have the luxury to ship [non-standard additions to the spec](https://github.com/rachelandrew/multicol-wip/issues/5) like Apple did – since their pagination API is relying on CSS multicol. 

I guess that, as we expected a few months ago, the transition may be causing some confusion.

**Comment by toshiakikoike** [comment] 2020-02-20 09:10
This issue may contain several different issues.

(1) skip to the head of spine items

I consider two different causes for this phenomenon.

(1-1) time lag
before loading and rendering the xhtml, the left button is clicked.


(1-2) the xhtml don't have lower level headings
for example, following xhtmls have only one heading, and are never pagenated.
- text/book_0002.xhtml
- text/book_0003.xhtml
- text/book_0010.xhtml
- text/book_0011.xhtml


(2) page-progression is top to bottom
I understand the CSS spec.
But the slide effect from top to bottom seems strange.
In that case, I think it is better to switch to the next page immediately without the slide effect if possible.

Then one more issue,
the location / position bar's direction is reversed.
pages fowarding to left, but ocation / position bar forwarding to right.

**Comment by danielweck** [comment] 2020-02-21 12:01
> (2) page-progression is top to bottom - I understand the CSS spec. But the slide effect from top to bottom seems strange. In that case, I think it is better to switch to the next page immediately without the slide effect if possible.

I totally agree. I noticed this bug too when I was testing a Japanese book. The solution is to disable visual animated transitions, because of the CSS columns being stacked on the horizontal axis.

**Comment by danielweck** [comment] 2020-02-21 12:02
> (1) skip to the head of spine items

This is likely an erroneous calculation in the column positioning. I am aware of this bug in Japanese books, but due to lack of time I haven't investigated this problem properly yet.

**Comment by danielweck** [comment] 2020-02-21 12:04
> Then one more issue, the location / position bar's direction is reversed.

Indeed, this is wrong.

**Comment by danielweck** [comment] 2022-08-26 14:13
Merged from https://github.com/edrlab/thorium-reader/issues/327

=>

Version: v1.0.0-alpha.2(Release Version)
Sample EPUB:
https://github.com/toshiakikoike/epub_file/blob/master/mymedia.epub
Sample Source:
https://github.com/toshiakikoike/epub_file/tree/master/mymedia

Problem: Cannot go to next page after Page3(https://github.com/toshiakikoike/epub_file/blob/master/mymedia/OEBPS/text/book_0002.xhtml)

Images:
Page1: OK(Only one Image)
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium002.png?raw=true">
Page:2: OK(Only one line)
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium003.png?raw=true">
Page:3: NG(Many Paragraphs) Cannot go to next page by clicking left triangle icon.
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium004.png?raw=true">

**Comment by danielweck** [comment] 2022-08-26 15:05
Merge from https://github.com/edrlab/thorium-reader/issues/1245

Hi.
I found bad layout result in vertical book. 
source: http://umetake.d.dooo.jp/kindle/download/Miserables.epub
Environment: Thorium-1.6.0-alpha.1.323935906

This problem seems to occur when the screen is small or the text is large with paged mode. The central block of text has margin indentation by div. When a line break occurs in the block, it causes an overlap with subsequent text. 

The shot below corresponds to the range from id="kobo.97.1" to id="kobo.119.1" of 0006.xhtml in EPUB Package. (8/59 6% on above shot)

OK shot:
<img width="1442" alt="ok" src="https://user-images.githubusercontent.com/3982249/97673063-785edc80-1ace-11eb-9fb1-952d5b60668f.png">

Invalid shot: Flowed text overlaps with subsequent paragraph.
<img width="1360" alt="invalid" src="https://user-images.githubusercontent.com/3982249/97673071-7ac13680-1ace-11eb-86f3-058877bc4c11.png">


Hmm. 
I'm not a web engineer so I don't know if I can provide accurate information. 

Anyway, I'm attaching the Web Inspector results when viewed in Safari Chrome. This picture is purely displaying the source HTML in the EPUB package and does not incorporate Readium-CSS.

Additionally, I have try to insert column-width property in < body > manually, this dose *not* cause any problems. 

Does this give you a hint?

Safari:
<img width="1585" alt="safari inspector" src="https://user-images.githubusercontent.com/3982249/97681129-22446600-1adb-11eb-9b2d-112b0dbdd369.png">

Chrome:
<img width="1227" alt="chrome inspector" src="https://user-images.githubusercontent.com/3982249/97681157-240e2980-1adb-11eb-81b0-4855551bc9de.png">

I've probably found cause of problem so I'll tell you.

I tried to modify --RS__maxMediaHeight to 1000vw in my test html, this makes correct result. So I think it's because the size of div is limited by max-width in ReadiumCSS-before. I don't know what the right value to put here is for me, but I think the cause is right in this.

**Comment by danielweck** [comment] 2022-08-26 17:57
Issue merged https://github.com/edrlab/thorium-reader/issues/1163

Vertical books may not be fully supported yet, but I report.
For example, the following vertical book.

- https://idpf.github.io/epub3-samples/30/samples.html#kusamakura

Opening it in paginated mode, the bottom character disappeared a little like the attached image. (The same thing happened in other books.)

![thorium-examples-kusamakura-bottom](https://user-images.githubusercontent.com/1066782/92434906-fd6afb00-f1db-11ea-9a1b-19f1d4688b4b.jpg)

In the scroll bar area, it seems that the characters are hidden. (The following is the same book opened in scrollable mode.)

![thorium-examples-kusamakura-bottom-scrolled](https://user-images.githubusercontent.com/1066782/92434910-02c84580-f1dc-11ea-974c-971203b5ae34.jpg)

p.s.
In scrollable mode, the scroll bar and the bottom character touch each other, so I think it difficult to read the book.

**Comment by danielweck** [comment] 2022-08-26 18:54
Merged issue: https://github.com/edrlab/thorium-reader/issues/1545

Thorium now renders both base and ruby without parentheses surrounding ruby.  This is not easy to read and, in rare cases, completely changes the meaning.

I recommend (1) rendering base only, and (2) rendering both base and ruby with surrounding parentheses added.

**Comment by danielweck** [comment] 2024-05-03 09:13
Fixed in Thorium 2.4

**Closed by danielweck** 2024-05-03 09:13 UTC
Labels: CJK
